import type { Achievement } from '../types'

export const CATEGORIES = [
  'Festival',
  'Racing & Events',
  'Exploration',
  'Stories',
  'Multiplayer',
  'Hot Wheels',
  'Rally Adventure',
  'Hide & Seek',
  'Horizon Realms',
]

export const achievements: Achievement[] = [

  // ── Festival (21) ──

  {
    id: 'welcome_to_mexico',
    name: 'Welcome to México',
    desc: 'Arrive at Horizon Festival México.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Story related, cannot be missed. Complete the opening sequence to arrive at the Horizon Festival.',
  },
  {
    id: 'race_into_action',
    name: 'Race into Action',
    desc: 'Complete any Horizon Race Event.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Win or complete any race event on the map. Unlocks very early in the game.',
  },
  {
    id: 'adaptable',
    name: 'Adaptable',
    desc: 'Complete the On a Wing and a Prayer Showcase Event.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete the first Showcase Event — a race against a fighter jet. This is one of the first events available on the map.',
  },
  {
    id: 'icebreaker',
    name: 'Icebreaker',
    desc: 'Participate in a Horizon Arcade Event.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Join any Horizon Arcade event. These are open-world multiplayer mini-events shown as glowing areas on the map. You can play solo or with other players online.',
  },
  {
    id: 'mi_casa',
    name: 'Mi Casa',
    desc: 'Unlock the first Player House.',
    tier: 'bronze',
    category: 'Festival',
    guide: "Purchase your first Player House. The first one (La Casa Solariega) costs 1.5 million CR and unlocks additional wheelspins and a fast travel point.",
  },
  {
    id: 'first_love',
    name: 'First Love',
    desc: 'Purchase your first car from the Autoshow.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Open the Autoshow from the main menu and purchase any car with Credits.',
  },
  {
    id: 'this_is_the_way',
    name: 'This Is The Way',
    desc: 'Start a new chapter of the Horizon Adventure.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Unlock a new Adventure chapter by completing events in any discipline (Wilds, Street Scene, Apex, Baja, or Rush).',
  },
  {
    id: 'viva_horizon',
    name: 'Viva Horizon!',
    desc: 'Unlock your first Horizon Finale Event.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete enough events in one discipline to unlock a Finale event. Progress through Road Racing, Dirt, Cross Country, Street Scene, or Off-Road events.',
  },
  {
    id: 'awdyssey',
    name: 'AWDyssey',
    desc: 'Build the Horizon Wilds Outpost.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete the Horizon Wilds Adventure chapter to build the Wilds Outpost. This unlocks the Cross Country and Dirt race events in that region.',
  },
  {
    id: 'ask_any_racer',
    name: 'Ask Any Racer, Any Real Racer',
    desc: 'Build the Horizon Street Scene Outpost.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete the Horizon Street Scene Adventure chapter to build the Street Scene Outpost.',
  },
  {
    id: 'far_from_mudding_crowd',
    name: 'Far from the Mudding Crowd',
    desc: 'Build the Horizon Apex Outpost.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete the Horizon Apex Adventure chapter to build the Apex Outpost.',
  },
  {
    id: 'theres_always_money',
    name: "There's Always Money in the Baja Stand",
    desc: 'Build the Horizon Baja Outpost.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete the Horizon Baja Adventure chapter to build the Baja Outpost.',
  },
  {
    id: 'adrenaline_rush',
    name: 'Adrenaline Rush',
    desc: 'Build the Horizon Rush Outpost.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete the Horizon Rush Adventure chapter to build the Rush Outpost.',
  },
  {
    id: 'hall_of_famer',
    name: 'Hall of Famer',
    desc: 'Reach the Horizon Hall of Fame.',
    tier: 'gold',
    category: 'Festival',
    guide: 'Earn enough Horizon XP to reach the Hall of Fame. This requires completing a large number of events and earning Influence across all disciplines. Expect this to take 20–30+ hours of play.',
  },
  {
    id: 'new_tune',
    name: 'New Tune',
    desc: 'Find a place to install the Horizon Pulse Radio Beacon.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'This is part of a story mission added via an update. Complete the mission to install the Radio Beacon and unlock a new radio station.',
  },
  {
    id: 'no_stone_unturned',
    name: 'No Stone Unturned',
    desc: 'Complete your first Expedition.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Complete any Expedition event. Expeditions become available after progressing through the main adventure and involve exploring new regions of México.',
  },
  {
    id: 'badge_of_honour',
    name: 'Badge of Honour',
    desc: 'Earn a Badge.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Earn any Badge from the Badges menu. Badges are cosmetic rewards earned by completing specific milestones (e.g. drive a certain distance, earn a skill chain, etc.).',
  },
  {
    id: 'manufacturer_affinity',
    name: 'Manufacturer Affinity',
    desc: 'Earn a Manufacturer Bonus.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Earn a Manufacturer Bonus by owning multiple cars from the same manufacturer. The bonus appears automatically as you accumulate cars from the same brand.',
  },
  {
    id: 'you_could_say_im_a_fan',
    name: "You Could Say I'm a Fan",
    desc: 'Earn a Manufacturer Bonus for a collection of 25 or more cars.',
    tier: 'silver',
    category: 'Festival',
    guide: 'Own 25 or more cars from the same manufacturer to earn the maximum Manufacturer Bonus. Focus on a brand with many affordable options (e.g. Ford, Chevrolet, or Toyota).',
  },
  {
    id: 'mogul',
    name: 'Mogul',
    desc: 'Purchase all 7 Player Houses.',
    tier: 'silver',
    category: 'Festival',
    guide: "Purchase all 7 Player Houses. The cheapest costs 1.5M CR and the most expensive costs 5M CR. Each house provides wheelspins, fast travel points, and other bonuses. Total cost is around 17M CR.",
  },
  {
    id: 'a_forza_edition',
    name: 'A Forza Edition to my Collection',
    desc: 'Earn a Forza Edition car from a Wheelspin or Super Wheelspin.',
    tier: 'bronze',
    category: 'Festival',
    guide: 'Forza Edition cars have a golden badge and appear randomly in Wheelspins and Super Wheelspins. Spin regularly and one will come eventually — Super Wheelspins have better odds.',
  },

  // ── Racing & Events (16) ──

  {
    id: 'putting_on_a_show',
    name: 'Putting on a Show',
    desc: 'Win every Showcase Event.',
    tier: 'gold',
    category: 'Racing & Events',
    guide: 'Win all Showcase Events in the base game — spectacular races against unique opponents like jets, trains, and hovercraft. There are around 10 Showcases in the base game. Each requires a specific car class — check the requirements before starting.',
  },
  {
    id: 'racing_and_pacing',
    name: 'Racing and Pacing and Plotting the Course',
    desc: 'Win 80 different Race Events in México.',
    tier: 'gold',
    category: 'Racing & Events',
    guide: 'Win 80 unique race events across the map. Each event only counts once. Work through all Road Racing, Dirt, Cross Country, and Street events. Enabling the Drivatar difficulty to a level you can consistently beat will help.',
  },
  {
    id: 'unbeatable_triumph',
    name: 'Unbeatable Triumph',
    desc: 'Win 6 different Race Events against Unbeatable Drivatars.',
    tier: 'silver',
    category: 'Racing & Events',
    guide: 'Set the difficulty to Unbeatable and win 6 different race events. Use a highly tuned S2 or X-Class car and pick shorter races to reduce the time needed. The Drivatar setting can be changed per-race.',
  },
  {
    id: 'living_legend',
    name: 'Living Legend',
    desc: 'Earn 294 stars from PR Stunts in México.',
    tier: 'gold',
    category: 'Racing & Events',
    guide: 'Earn 3 stars (the maximum) on all 98 PR Stunts in the base game — Speed Cameras, Speed Traps, Danger Signs, and Trailblazers. Each stunt shows the 3-star target in-game. Track progress via the map. Requires well-tuned cars for each stunt type.',
  },
  {
    id: 'i_have_the_high_ground',
    name: 'I Have the High Ground',
    desc: 'Win 3 Rivals Events in 3 different PI Classes while driving the same car.',
    tier: 'silver',
    category: 'Racing & Events',
    guide: 'Post a clean Rivals time that beats the ghost in 3 different PI classes using the same car. Tune the same car to C, B, and A class (or any 3 classes) and beat the rival ghost in each. Rivals events are in the online/connected menu.',
  },
  {
    id: 'long_gone',
    name: 'Long Gone',
    desc: 'Win the Goliath Race Event.',
    tier: 'silver',
    category: 'Racing & Events',
    guide: "Win the Goliath — a massive circuit that covers most of México's roads and takes around 30–40 minutes per lap. Use an X-Class car. The Goliath unlocks after reaching the Hall of Fame. Set Drivatars to Easy for a stress-free win.",
  },
  {
    id: 'ford_of_the_wings',
    name: 'Ford of the Wings',
    desc: "Earn 3 Stars at the Eagle's Perch Danger Sign in a Ford Supervan 3.",
    tier: 'bronze',
    category: 'Racing & Events',
    guide: "Find the Eagle's Perch Danger Sign (near the mountains in northern México) and earn 3 stars using the Ford Supervan 3 specifically. The Supervan 3 can be purchased from the Autoshow. Tune it for maximum speed/launch.",
  },
  {
    id: 'water_performance',
    name: 'Water Performance',
    desc: 'Earn 3 stars at the Puerta Pétrea and La Marisma Trailblazers within 3 minutes and 30 seconds.',
    tier: 'bronze',
    category: 'Racing & Events',
    guide: 'Complete both Trailblazer stunts (Puerta Pétrea and La Marisma) back-to-back within 3:30 total. Both are in the coastal wetlands area. Use a fast AWD car and drive directly between them after completing the first.',
  },
  {
    id: 'tourist_attraction',
    name: 'Tourist Attraction',
    desc: 'Complete your first Horizon Tour Race Event.',
    tier: 'bronze',
    category: 'Racing & Events',
    guide: 'Join a Horizon Tour event from the online multiplayer menu. These are multi-race series against other players. Complete any single race in a Tour event.',
  },
  {
    id: 'min_meet_max',
    name: 'Min, Meet Max',
    desc: 'Complete all Events in a Festival Playlist Series.',
    tier: 'silver',
    category: 'Racing & Events',
    guide: 'During any active Festival Playlist season, complete every event listed in the Series tab. This includes online championships, PR stunts, and special events. The Playlist resets each week, so track your progress within a single season.',
  },
  {
    id: 'seasoned_veteran',
    name: 'Seasoned Veteran',
    desc: 'Complete a Festival Playlist activity in every season.',
    tier: 'silver',
    category: 'Racing & Events',
    guide: "Complete at least one Playlist activity in Spring, Summer, Autumn, and Winter. Each season lasts one week in real time and cycles automatically. Simply log in and complete one event per season across four consecutive weeks.",
  },
  {
    id: 'treasure_hunter',
    name: 'Treasure Hunter',
    desc: 'Find all Treasure Chests in a Festival Playlist Series.',
    tier: 'silver',
    category: 'Racing & Events',
    guide: 'During a Festival Playlist season, find all Treasure Chests marked on the map. They appear as chest icons and require specific in-game actions to unlock (usually driving to them and interacting).',
  },
  {
    id: 'front_runner',
    name: 'Front Runner',
    desc: 'Finish 5 Horizon Tour Race Events ahead of all Drivatars.',
    tier: 'silver',
    category: 'Racing & Events',
    guide: 'Finish first in 5 separate Horizon Tour race events (multiplayer). Use a well-tuned car in the required class and race aggressively from the start.',
  },
  {
    id: 'unlimited_prowess',
    name: 'Unlimited Prowess!',
    desc: 'Complete Round Three in all 5 Themes of Horizon Arcade.',
    tier: 'gold',
    category: 'Racing & Events',
    guide: "Reach and complete Round 3 in each of the 5 Arcade themes: Rush Hour, Juggernaut, Air Strike, Piñata Pop, and Virus. Round 3 is the final round and requires enough players contributing points. Best done online — find an active session or use a convoy.",
  },
  {
    id: 'gotta_smash_em_all',
    name: "Gotta Smash 'Em All",
    desc: 'Complete 5 Seasonal Smashable Challenges.',
    tier: 'bronze',
    category: 'Racing & Events',
    guide: 'During seasonal events, specific Smashable Challenges appear on the map (objects to destroy). Complete 5 of these across any combination of seasons.',
  },
  {
    id: 'cactus_makes_perfect',
    name: 'Cactus Makes Perfect',
    desc: "Smash 500 cacti during México's Wet Season.",
    tier: 'bronze',
    category: 'Racing & Events',
    guide: "During the in-game Wet Season (one of the four rotating seasons), drive off-road and smash 500 cacti. Cacti are abundant throughout the Mexican landscape. This is cumulative across multiple Wet Season periods.",
  },

  // ── Exploration (11) ──

  {
    id: 'ride_and_seek',
    name: 'Ride and Seek',
    desc: 'Discover and drive every road in México.',
    tier: 'gold',
    category: 'Exploration',
    guide: "Drive every road in the base game map. Roads turn from grey to coloured on the minimap once driven. Use the full map to identify undriven roads (grey lines). This is very time-consuming — expect several hours of dedicated exploration. The Horizon Pulse update adds additional roads.",
  },
  {
    id: 'complete_collection',
    name: 'Complete Collection',
    desc: 'Find and smash all 250 Bonus Boards in México.',
    tier: 'gold',
    category: 'Exploration',
    guide: 'Find and smash all 250 Bonus Boards scattered across México. These include XP Boards, Fast Travel Boards, and Super Wheelspin Boards. Use an online guide or the game map to track locations. Smashing Fast Travel Boards reduces the fast travel cost.',
  },
  {
    id: 'better_than_new',
    name: 'Better Than New',
    desc: 'Restore 14 Barn Finds in México.',
    tier: 'silver',
    category: 'Exploration',
    guide: 'Discover and restore all 14 Barn Finds in the base game. Listen to radio hints that unlock barn locations on the map. Drive to each barn to claim the car, then wait for the timer to complete the restoration.',
  },
  {
    id: 'an_item_of_extreme_value',
    name: 'An Item Of Extreme Value',
    desc: 'Discover and photograph the Golden Tlaloc Totem.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Find the Golden Tlaloc Totem hidden somewhere in México and photograph it using Photo Mode. Check online guides for the exact location — it's a large golden statue in a hard-to-reach area.",
  },
  {
    id: 'album_cover',
    name: 'Album Cover',
    desc: 'Take a photo of the 2021 Mercedes-AMG ONE for Horizon Promo.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'Own or borrow the 2021 Mercedes-AMG ONE (available from the Autoshow) and take a photo of it when prompted for Horizon Promo. Horizon Promo photo requests appear in the game world as blue camera icons.',
  },
  {
    id: 'fit_to_print',
    name: 'Fit to Print',
    desc: 'Take 50 photos of Legendary cars for Horizon Promo.',
    tier: 'silver',
    category: 'Exploration',
    guide: 'Photograph 50 different Legendary cars for Horizon Promo. Legendary cars are the rarest tier — check the Autoshow filter for Legendary cars. This requires owning or being near many different Legendary vehicles.',
  },
  {
    id: 'a_royal_affair',
    name: 'A Royal Affair',
    desc: 'At sunrise, take a photo of your car with some monarch butterflies at Hotel Mirador Balderrama.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Drive to Hotel Mirador Balderrama in the Guanajuato region. Set the time to Sunrise in Photo Mode (or wait for in-game sunrise). Monarch butterflies appear near the hotel — include them and your car in the shot.",
  },
  {
    id: 'dust_in_the_lens',
    name: 'Dust in the Lens',
    desc: 'Take a photo featuring the Gran Telescopio and a dust storm.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'Drive to the Gran Telescopio Canarias (the giant telescope on the map, north of the map). Wait for a dust storm weather event, then enter Photo Mode and frame both the telescope and the dust storm.',
  },
  {
    id: 'stunning_photography',
    name: 'Stunning Photography',
    desc: 'Take a photo during a tropical storm.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'Wait for the in-game weather to produce a tropical storm (common in Summer season). Enter Photo Mode during the storm and take any photo. If you cannot wait, set the time to Summer in a new game session.',
  },
  {
    id: 'a_heart_of_gold',
    name: 'A Heart of Gold',
    desc: 'Send another player a Gift Drop.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Open the Gift Drops menu (in the Horizon Life section) and send any car to another player. You can gift cars from your garage — even cheap cars count.",
  },
  {
    id: 'good_carma',
    name: 'Good Carma',
    desc: 'Give another player some Kudos to show your appreciation.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "After completing a multiplayer event or driving near another player's car, use the Kudos option to give them a thumbs up. This can also be done from post-race screens.",
  },

  // ── Stories (21) ──

  {
    id: 'how_to_race_friends',
    name: 'How to Race Friends and Influence People',
    desc: "Earn 3 stars in the 'Tristan' Chapter of the 'Born Fast' Horizon Story.",
    tier: 'silver',
    category: 'Stories',
    guide: "In the 'Born Fast' Horizon Story, earn 3 stars in the Tristan chapter. This typically involves winning a race while meeting specific conditions (e.g. no rewinds, beat a certain time). Retry the chapter if needed.",
  },
  {
    id: 'cover_to_cover',
    name: 'Cover to Cover',
    desc: 'Earn 3 stars on all chapters in a single Horizon Story.',
    tier: 'gold',
    category: 'Stories',
    guide: "Earn 3 stars on every chapter in any one Horizon Story. The easiest candidates are 'Born Fast' and 'Horizon Origins'. Each chapter has specific conditions for 3 stars — usually win the race and meet bonus objectives.",
  },
  {
    id: 'hoonigan_impressionist',
    name: 'Hoonigan Impressionist',
    desc: "Smash a Pinata in the 'Drift Club Mexico' Chapter of the 'Drift Club' Horizon Story.",
    tier: 'bronze',
    category: 'Stories',
    guide: "Start the 'Drift Club' Horizon Story and reach the 'Drift Club Mexico' chapter. During this chapter, piñatas appear on the course — drive into one to smash it and unlock the achievement.",
  },
  {
    id: 'join_the_club',
    name: 'Join the Club',
    desc: "Complete all chapters of the 'Drift Club' Horizon Story.",
    tier: 'silver',
    category: 'Stories',
    guide: "Complete every chapter in the Drift Club Horizon Story. The Drift Club is accessed from the Horizon Stories menu. Each chapter requires drifting and accumulating a target score.",
  },
  {
    id: 'drift_club_mexico',
    name: 'Drift Club Mexico',
    desc: "Earn 3 stars in all chapters of the 'Drift Club' Horizon Story.",
    tier: 'gold',
    category: 'Stories',
    guide: "Earn 3 stars on every chapter of the Drift Club Horizon Story. Each chapter has specific 3-star conditions. Use a well-tuned RWD drift car and practice each chapter. Retry chapters as needed.",
  },
  {
    id: 'welcome_to_mexico_2',
    name: 'Welcome to Mexico 2.0',
    desc: "Complete the 'Welcome to Mexico' chapter of the 'Horizon Origins' Story.",
    tier: 'bronze',
    category: 'Stories',
    guide: "Start the 'Horizon Origins' Horizon Story and complete the first chapter 'Welcome to Mexico'.",
  },
  {
    id: 'smash_happy',
    name: 'Smash Happy',
    desc: "Smash all 4 Bonus Boards in the 'Horizon Origins' Story.",
    tier: 'bronze',
    category: 'Stories',
    guide: "While playing through the 'Horizon Origins' Horizon Story, find and smash all 4 Bonus Boards hidden within the story missions. They are marked by board icons during the story events.",
  },
  {
    id: 'blast_from_the_past',
    name: 'Blast From the Past',
    desc: "Complete all chapters of the 'Horizon Origins' Story.",
    tier: 'silver',
    category: 'Stories',
    guide: "Complete all chapters of the Horizon Origins Horizon Story. This story follows the history of Forza Horizon using iconic cars from past Horizon games.",
  },
  {
    id: 'memory_lane',
    name: 'Memory Lane',
    desc: "Earn 3 stars in all chapters of the 'Horizon Origins' Story.",
    tier: 'gold',
    category: 'Stories',
    guide: "Earn 3 stars on every chapter of the Horizon Origins Horizon Story. Each chapter requires winning a race while meeting specific bonus conditions.",
  },
  {
    id: 'ill_just_take_this_now',
    name: "I'll Just Take This Now",
    desc: 'Win your first Midnight Battle.',
    tier: 'bronze',
    category: 'Stories',
    guide: 'Find and win a Midnight Battle — underground street racing events that appear at night on specific roads. Drive to a glowing area on the map at night and challenge the NPC racer.',
  },
  {
    id: 'nighthawk',
    name: 'Nighthawk',
    desc: 'Win every Midnight Battle.',
    tier: 'silver',
    category: 'Stories',
    guide: 'Win all Midnight Battle events scattered across México. These only appear at night and involve racing specific NPC rivals. Use highly tuned cars appropriate to each battle.',
  },
  {
    id: 'made_in_mexico',
    name: 'Made in Mexico',
    desc: "Complete all chapters of the 'Made in Mexico' Horizon Story.",
    tier: 'silver',
    category: 'Stories',
    guide: "Complete all chapters of the Made in Mexico Horizon Story. This story celebrates Mexican car culture and includes off-road and street events.",
  },
  {
    id: 'vuhl',
    name: 'V.U.H.L',
    desc: "Earn 3 stars in all chapters of the 'Made in Mexico' Horizon Story.",
    tier: 'gold',
    category: 'Stories',
    guide: "Earn 3 stars on every chapter of the Made in Mexico Horizon Story. The VUHL 05RR is featured in this story — ensure your car is well-tuned for 3-star conditions.",
  },
  {
    id: 'on_the_road_again',
    name: 'On the Road Again',
    desc: 'Complete the first chapter of the Donut Media HiLow Story.',
    tier: 'bronze',
    category: 'Stories',
    guide: 'Start the Donut Media HiLow Story (available from Horizon Stories) and complete the first chapter.',
  },
  {
    id: 'hi_five',
    name: 'Hi Five',
    desc: 'Complete all chapters of the Donut Media Hi Story.',
    tier: 'silver',
    category: 'Stories',
    guide: 'Complete all chapters of the High Budget (Hi) path in the Donut Media HiLow Story. This path features expensive, high-performance cars.',
  },
  {
    id: 'low_five',
    name: 'Low Five',
    desc: 'Complete all chapters of the Donut Media Low Story.',
    tier: 'silver',
    category: 'Stories',
    guide: 'Complete all chapters of the Low Budget (Low) path in the Donut Media HiLow Story. This path features cheap, modified budget cars.',
  },
  {
    id: 'give_it_the_beans',
    name: 'Give it the Beans!',
    desc: 'Earn 3 Stars on all chapters of both Hi and Low stories.',
    tier: 'gold',
    category: 'Stories',
    guide: 'Earn 3 stars on every chapter across both the Hi and Low paths of the Donut Media HiLow Story. This requires replaying chapters to meet all 3-star conditions in both storylines.',
  },
  {
    id: 'back_to_school',
    name: 'Back To School',
    desc: 'Complete the first chapter in the Icons of Speed Story.',
    tier: 'bronze',
    category: 'Stories',
    guide: 'Start the Icons of Speed Horizon Story and complete the first chapter.',
  },
  {
    id: 'a_new_era',
    name: 'A New Era',
    desc: 'Complete all chapters in the Icons of Speed Story.',
    tier: 'silver',
    category: 'Stories',
    guide: 'Complete all chapters of the Icons of Speed Horizon Story. This story features iconic road cars and hypercars across multiple events.',
  },
  {
    id: 'a_true_icon',
    name: 'A True Icon',
    desc: 'Earn 3 Stars in all chapters of the Icons of Speed Story.',
    tier: 'gold',
    category: 'Stories',
    guide: 'Earn 3 stars on every chapter of the Icons of Speed Horizon Story. Each chapter requires winning and meeting bonus objectives.',
  },

  // ── Multiplayer (12) ──

  {
    id: 'youre_the_champion',
    name: "You're the Champion",
    desc: 'Win any Event in Horizon Open.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Join Horizon Open from the online menu and win any event. Open Racing, Drift, and Custom racing are all available. Use a well-tuned car in the required class.',
  },
  {
    id: 'the_grand_opening',
    name: 'The Grand Opening',
    desc: 'Earn 10 Levels in Horizon Open.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Earn 10 level-ups in Horizon Open by participating in races. XP is earned simply by completing events — wins earn more but participation counts too.',
  },
  {
    id: 'another_one_bites_the_dust',
    name: 'Another One Bites the Dust',
    desc: 'Earn 100 Levels in Horizon Open.',
    tier: 'gold',
    category: 'Multiplayer',
    guide: 'Earn 100 level-ups in Horizon Open. This requires substantial time playing online races. Each level requires progressively more XP. Winning races consistently is the fastest approach.',
  },
  {
    id: 'back_in_the_saddle',
    name: 'Back in the Saddle',
    desc: 'Complete a Horizon Open Custom Race in the 2021 Ford Bronco.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Own the 2021 Ford Bronco, then join a Horizon Open Custom Race (where car selection is free-choice) and complete the race while driving it.',
  },
  {
    id: 'one_for_all',
    name: 'One for All',
    desc: 'Complete a Horizon Open Custom Race in the 2021 Mercedes-AMG One.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Own the 2021 Mercedes-AMG One (available from the Autoshow for ~2M CR), join a Horizon Open Custom Race, and complete any race while driving it.',
  },
  {
    id: 'chicken_dinner',
    name: 'Chicken Dinner',
    desc: 'Win your first game of The Eliminator.',
    tier: 'silver',
    category: 'Multiplayer',
    guide: 'Join The Eliminator (a battle royale event in Horizon Life) and be the last player standing. Win by out-driving and eliminating other players in head-to-head challenges. Use upgraded cars found during the event.',
  },
  {
    id: 'jackpot',
    name: 'Jackpot',
    desc: 'Fully complete a run of Super7.',
    tier: 'silver',
    category: 'Multiplayer',
    guide: 'Complete all 7 challenges in a single Super7 run. Super7 is accessed from Horizon Life and presents 7 increasingly difficult stunt/skill challenges. Completing all 7 in one session counts.',
  },
  {
    id: 'show_me_your_moves',
    name: 'Show Me Your Moves!',
    desc: 'Play any EventLab Event created by another player.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Browse and join any EventLab event created by the community. Access EventLab from the Horizon Life menu. Simply complete or participate in any community-created event.',
  },
  {
    id: 'get_my_good_side',
    name: 'Get My Good Side',
    desc: 'Take a photo of your character outside a car.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: "In Photo Mode, position the camera to include your character standing outside their car. You'll need to exit the car first (not possible in standard driving) — use the Photo Mode free camera to frame the character near the car.",
  },
  {
    id: 'juuuuust_right',
    name: 'Juuuuust Right',
    desc: 'Take a photo using any guidelines 3 times.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'In Photo Mode, enable any of the composition guidelines (Rule of Thirds, Golden Ratio, etc.) from the settings and take 3 photos with guidelines active.',
  },
  {
    id: 'timeless',
    name: 'Timeless',
    desc: 'Take a photo at every time setting.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'In Photo Mode, use the time-of-day slider to take photos at all available time settings: Dawn, Sunrise, Morning, Midday, Afternoon, Sunset, Dusk, and Night.',
  },
  {
    id: 'give_me_five',
    name: 'Give Me Five!',
    desc: 'Apply and purchase an upgrade to 5 cars at the Horizon Test Track.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Visit the Horizon Test Track (from the Test & Tune menu) and upgrade 5 different cars while there. The Test Track allows you to test and tune cars before purchase.',
  },

  // ── Hot Wheels DLC (27) ──

  {
    id: 'no_one_expects_hw',
    name: 'No One Expects the Hot Wheels Expedition',
    desc: 'Arrive at the Horizon Hot Wheels Outpost.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Complete the Expedition that unlocks the Hot Wheels DLC area. The Expedition begins automatically when the Hot Wheels DLC is installed.',
  },
  {
    id: 'the_rookie',
    name: 'The Rookie',
    desc: 'Complete the Rookie Qualifier Event.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Complete the Rookie Qualifier race event in Hot Wheels Park. This is one of the early events that unlocks access to the full Hot Wheels circuit.',
  },
  {
    id: 'pros_no_cons',
    name: 'Pros, No Cons',
    desc: 'Complete the Pro Qualifier Event.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Complete the Pro Qualifier race event in Hot Wheels Park.',
  },
  {
    id: 'im_an_expert_now',
    name: "I'm an Expert Now",
    desc: 'Complete the Expert Qualifier Event.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Complete the Expert Qualifier race event in Hot Wheels Park.',
  },
  {
    id: 'wort_wort_wort',
    name: 'WORT, WORT, WORT!',
    desc: 'Complete the Elite Qualifier Event.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Complete the Elite Qualifier — the toughest Qualifier event in Hot Wheels Park. Requires a high PI car and strong driving on the advanced orange track layouts.',
  },
  {
    id: 'hot_wheels_legend',
    name: 'Hot Wheels Legend',
    desc: 'Win the Hot Wheels Goliath event and become the Hot Wheels Legend.',
    tier: 'gold',
    category: 'Hot Wheels',
    guide: 'Win the Hot Wheels Goliath — a massive circuit through the entire Hot Wheels Park. This is the main finale event of the DLC. Use a high-PI car and set difficulty to Easy for the best chance.',
  },
  {
    id: 'missions',
    name: 'Missions!',
    desc: 'Complete 5 Missions.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Complete 5 Missions in Hot Wheels Park. Missions are unique challenges scattered throughout the park.',
  },
  {
    id: 'more_missions',
    name: 'More Missions!',
    desc: 'Complete 25 Missions.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Complete 25 Missions in Hot Wheels Park. Work through all available missions across the park.',
  },
  {
    id: 'missions_complete',
    name: 'Missions Complete!',
    desc: 'Complete All Missions.',
    tier: 'gold',
    category: 'Hot Wheels',
    guide: 'Complete every Mission in Hot Wheels Park. Check the mission list for any missed challenges.',
  },
  {
    id: 'over_qualified',
    name: 'Over-Qualified',
    desc: 'Earn 3 Stars from each of the Hot Wheels Qualifier events.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Earn 3 stars on all 4 Qualifier events (Rookie, Pro, Expert, Elite). Each requires winning with specific conditions met. Use high-PI cars for Expert and Elite.',
  },
  {
    id: 'altitude_quickness',
    name: 'Altitude Quickness',
    desc: 'Win all Race Events.',
    tier: 'gold',
    category: 'Hot Wheels',
    guide: 'Win every Race Event in Hot Wheels Park. Work through all the orange-track race events across the park layout.',
  },
  {
    id: 'soared_and_board',
    name: 'Soared and Board',
    desc: 'Smash all Bonus Boards in Hot Wheels Park.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Find and smash every Bonus Board throughout Hot Wheels Park. Check online maps for board locations — some require specific jumps or track sections to access.',
  },
  {
    id: 'gotta_pop_em_all',
    name: "Gotta Pop 'Em All",
    desc: 'Smash all of the Floating Tanks in Hot Wheels Park.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Find all floating balloon tanks throughout Hot Wheels Park and smash them by driving into them. They are scattered at height on the elevated track sections.',
  },
  {
    id: 'fresh_pressed_orange_routes',
    name: 'Fresh Pressed Orange Routes',
    desc: 'Discover every road in Hot Wheels Park.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Drive every road and track section in Hot Wheels Park. The orange tracks all count — systematically drive every section until the map shows full coverage.',
  },
  {
    id: 'lessons_in_hw_history',
    name: 'Lessons in Hot Wheels History',
    desc: 'Complete the first Chapter of the Hot Wheels Horizon Story.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Start and complete the first chapter of the Hot Wheels Horizon Story, which covers the history and legacy of Hot Wheels.',
  },
  {
    id: 'major_in_hw_history',
    name: 'Major in Hot Wheels History',
    desc: 'Complete all Chapters in the Hot Wheels Horizon Story.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Complete every chapter in the Hot Wheels Horizon Story. The story spans multiple events across the park.',
  },
  {
    id: 'professor_of_hw_history',
    name: 'Professor of Hot Wheels History',
    desc: 'Earn 3 Stars from every Chapter in the Hot Wheels Horizon Story.',
    tier: 'gold',
    category: 'Hot Wheels',
    guide: 'Earn 3 stars on every chapter of the Hot Wheels Horizon Story. Each chapter requires winning and meeting bonus objectives.',
  },
  {
    id: 'competition_experimentation',
    name: 'Competition, Experimentation, and Creativity',
    desc: "Play another player's EventLab creation utilizing Hot Wheels track pieces.",
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: "Browse EventLab and filter for events using Hot Wheels track pieces. Join and complete any community-created event that uses the orange Hot Wheels track.",
  },
  {
    id: 'beach_bomb',
    name: 'Beach Bomb',
    desc: 'Earn 3 stars at the Canyon Jump Danger Sign in a 1963 Volkswagen Type 2 De Luxe.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: "Find the Canyon Jump Danger Sign in Hot Wheels Park and earn 3 stars using specifically the 1963 Volkswagen Type 2 De Luxe (the VW Bus). Tune it for maximum speed and use the full run-up.",
  },
  {
    id: 'aquanaut',
    name: 'Aquanaut',
    desc: 'Win any race that includes sections of Hot Wheels Water Flume Track.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Win any race event in Hot Wheels Park that routes through the Water Flume track sections (the blue waterslide-style track).',
  },
  {
    id: 'icy_roads_ahead',
    name: 'Icy Roads Ahead',
    desc: 'Win any race that includes sections of Hot Wheels Ice Track.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Win any race event in Hot Wheels Park that routes through the Ice Track sections.',
  },
  {
    id: 'shaken_not_third',
    name: 'Shaken Not Third',
    desc: 'Win any race that includes sections of Hot Wheels Rumble Track.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Win any race event in Hot Wheels Park that routes through the Rumble Track sections (the shaking, vibrating track type).',
  },
  {
    id: 'attracted_to_victory',
    name: 'Attracted to Victory',
    desc: 'Win any race that includes sections of Hot Wheels Magnet Track.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Win any race event in Hot Wheels Park that routes through the Magnet Track sections.',
  },
  {
    id: 'supersonic',
    name: 'Supersonic',
    desc: 'Finish a lap of the Hot Wheels Goliath event in under 6 minutes.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Complete a single lap of the Hot Wheels Goliath in under 6 minutes. Use an S2 or X-Class car tuned for high top speed. The loop sections and boost pads will help maintain speed.',
  },
  {
    id: 'points_mean_prizes',
    name: 'Points Mean Prizes',
    desc: 'Complete any Seasonal Activity in Hot Wheels Park.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'During any active Festival Playlist season, find and complete any Seasonal Activity located within Hot Wheels Park.',
  },
  {
    id: 'hot_wheels_hot_laps',
    name: 'Hot Wheels, Hot Laps',
    desc: 'Post a clean time for every Rivals route in Hot Wheels Park.',
    tier: 'silver',
    category: 'Hot Wheels',
    guide: 'Set a clean lap time on every Rivals route within Hot Wheels Park. A clean time requires completing the lap without significant wall contacts.',
  },
  {
    id: 'high_roller',
    name: 'High Roller',
    desc: 'Spin 25 Wheelspins while in Hot Wheels Park.',
    tier: 'bronze',
    category: 'Hot Wheels',
    guide: 'Earn and spin 25 Wheelspins while your base location is set to Hot Wheels Park. Wheelspins are earned from levelling up and completing milestones.',
  },
  {
    id: 'hot_wheels_all_star',
    name: 'Hot Wheels All Star',
    desc: 'Earn 3 Stars from every PR Stunt in Hot Wheels Park.',
    tier: 'gold',
    category: 'Hot Wheels',
    guide: 'Earn 3 stars on every PR Stunt (Danger Signs, Speed Traps, Speed Cameras, Trailblazers) in Hot Wheels Park. Use well-tuned S2-class cars for the best results.',
  },

  // ── Rally Adventure DLC (27) ──

  {
    id: 'welcome_to_sierra_nueva',
    name: 'Welcome to Sierra Nueva',
    desc: 'Arrive at the Horizon Badlands Outpost.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'Complete the Expedition that unlocks the Rally Adventure DLC area (Sierra Nueva). The Expedition begins automatically when the Rally Adventure DLC is installed.',
  },
  {
    id: 'rouen',
    name: 'Rouen',
    desc: 'Win your first Horizon Rally event.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'Win any Horizon Rally event in Sierra Nueva. Rally events are point-to-point stages with co-driver navigation.',
  },
  {
    id: 'better_together',
    name: 'Better Together',
    desc: 'Win your first Horizon Race event.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'Win any Horizon Race (circuit or sprint) event in Sierra Nueva.',
  },
  {
    id: 'its_rally_time',
    name: "It's Rally Time!",
    desc: 'Join the Horizon Raptors Team.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: "Join the Horizon Raptors team by selecting them from the team selection screen at the start of the Rally Adventure campaign.",
  },
  {
    id: 'road_rally',
    name: 'Road Rally',
    desc: 'Join the Apex Predators Team.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'Join the Apex Predators team. Note: you can only join one team per playthrough — restart a new campaign to join a different team if needed.',
  },
  {
    id: 'in_the_still_of_the_night',
    name: 'In The Still Of The Night',
    desc: 'Join the Grit Reapers Team.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'Join the Grit Reapers team. This requires starting a new Rally Adventure campaign if you previously chose another team.',
  },
  {
    id: 'pink_slip',
    name: 'Pink Slip',
    desc: 'Win your first Team Champion Race.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'Win any of the three Team Champion Races — the head-to-head races between team leaders in Sierra Nueva.',
  },
  {
    id: 'picking_up_the_tab',
    name: 'Picking Up The Tab',
    desc: 'Win all three Team Champion Races.',
    tier: 'silver',
    category: 'Rally Adventure',
    guide: 'Win all three Team Champion Races. Since each champion race represents one of the three teams, you may need to replay the campaign or choose different team paths across multiple playthroughs.',
  },
  {
    id: 'horizon_badlands_champion',
    name: 'Horizon Badlands Champion',
    desc: 'Become the Horizon Badlands Rally Champion.',
    tier: 'gold',
    category: 'Rally Adventure',
    guide: 'Complete the full Rally Adventure campaign to become the Horizon Badlands Rally Champion. This involves winning the final championship event in Sierra Nueva.',
  },
  {
    id: 'keep_calm_and_rally_on',
    name: 'Keep Calm And Rally On',
    desc: 'Win all Horizon Rally events.',
    tier: 'gold',
    category: 'Rally Adventure',
    guide: 'Win every Horizon Rally event in Sierra Nueva. These point-to-point stages cover the full variety of terrain in the region.',
  },
  {
    id: 'course_connoisseur',
    name: 'Course Connoisseur',
    desc: 'Win all Horizon Race events.',
    tier: 'gold',
    category: 'Rally Adventure',
    guide: 'Win every Horizon Race (circuit/sprint) event in Sierra Nueva.',
  },
  {
    id: 'backwards_at_night',
    name: 'Backwards, At Night, In The Rain',
    desc: "Complete all of Ramiro's Reputation Challenges.",
    tier: 'silver',
    category: 'Rally Adventure',
    guide: "Complete every Reputation Challenge associated with Ramiro (the Grit Reapers team leader). These are skill and driving challenges tied to his team's style.",
  },
  {
    id: 'follow_my_lead',
    name: 'Follow My Lead',
    desc: "Complete all of Alejandra's Reputation Challenges.",
    tier: 'silver',
    category: 'Rally Adventure',
    guide: "Complete every Reputation Challenge associated with Alejandra (the Horizon Raptors team leader).",
  },
  {
    id: 'i_aint_gonna_change',
    name: "I Ain't Gonna Change",
    desc: "Complete all of Alex's Reputation Challenges.",
    tier: 'silver',
    category: 'Rally Adventure',
    guide: "Complete every Reputation Challenge associated with Alex (the Apex Predators team leader).",
  },
  {
    id: 'completed_it_mate',
    name: 'Completed It Mate',
    desc: 'Complete all the Reputation Challenges.',
    tier: 'gold',
    category: 'Rally Adventure',
    guide: "Complete all Reputation Challenges for all three team leaders (Ramiro, Alejandra, and Alex). This requires completing every challenge regardless of which team you joined.",
  },
  {
    id: 'smashlicious',
    name: 'Smashlicious',
    desc: 'Smash 15 Apex Predators Boards.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'Find and smash 15 of the Apex Predators Boards scattered across Sierra Nueva.',
  },
  {
    id: 'generating_alternate_smash_flows',
    name: 'Generating Alternate Smash Flows',
    desc: 'Smash all 30 Apex Predators Boards.',
    tier: 'silver',
    category: 'Rally Adventure',
    guide: 'Find and smash all 30 Apex Predators Boards in Sierra Nueva. Use an online guide to locate all boards.',
  },
  {
    id: 'smashtastic',
    name: 'Smashtastic',
    desc: 'Smash 150 Piñata Trucks!',
    tier: 'silver',
    category: 'Rally Adventure',
    guide: 'Smash 150 Horizon Raptors Piñata Trucks driving around Sierra Nueva. These spawn during free roam — ram into them to smash them. This is cumulative across sessions.',
  },
  {
    id: 'put_it_on_my_smash_drive',
    name: 'Put it on my Smash Drive',
    desc: 'Smash 150 Grit Reapers Crates.',
    tier: 'silver',
    category: 'Rally Adventure',
    guide: 'Smash 150 Grit Reapers Crates scattered across Sierra Nueva. Drive into the yellow crates found throughout the region. Cumulative across sessions.',
  },
  {
    id: 'road_book',
    name: 'Road Book',
    desc: 'Discover every road in Sierra Nueva.',
    tier: 'gold',
    category: 'Rally Adventure',
    guide: 'Drive every road in the Sierra Nueva DLC map. Check the minimap for grey (undiscovered) roads. Systematically cover the entire region.',
  },
  {
    id: 'canyon_master',
    name: 'Canyon Master',
    desc: 'Earn 3 Stars from every freeroam PR Stunt in Sierra Nueva.',
    tier: 'silver',
    category: 'Rally Adventure',
    guide: 'Earn 3 stars on every PR Stunt (Speed Cameras, Danger Signs, Trailblazers, Speed Traps) in Sierra Nueva. Use high-PI cars tuned for each stunt type.',
  },
  {
    id: 'that_time_of_year',
    name: 'That Time of Year',
    desc: 'Complete any Seasonal Activity in Sierra Nueva.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'During any active Festival Playlist season, complete any Seasonal Activity located within Sierra Nueva.',
  },
  {
    id: 'unlimited_rally',
    name: 'Unlimited Rally',
    desc: 'Cross your first Split-Gate in a Horizon Rally event.',
    tier: 'bronze',
    category: 'Rally Adventure',
    guide: 'During a Horizon Rally event, reach and pass through a Split-Gate — an optional shortcut/alternate route that changes your stage time.',
  },
  {
    id: 'living_up_to_the_rep',
    name: 'Living up to the Rep',
    desc: "Make your way up to the 7th Tier of Horizon Raptors Reputation Challenges.",
    tier: 'silver',
    category: 'Rally Adventure',
    guide: "Progress through Reputation Challenges to reach Tier 7 on the Horizon Raptors team track.",
  },
  {
    id: 'just_reppin',
    name: "Just Reppin'",
    desc: "Make your way up to the 7th Tier of Apex Predators Reputation Challenges.",
    tier: 'silver',
    category: 'Rally Adventure',
    guide: "Progress through Reputation Challenges to reach Tier 7 on the Apex Predators team track.",
  },
  {
    id: 'cash_and_rally',
    name: 'Cash and Rally',
    desc: "Make your way up to the 7th Tier of Grit Reapers Reputation Challenges.",
    tier: 'silver',
    category: 'Rally Adventure',
    guide: "Progress through Reputation Challenges to reach Tier 7 on the Grit Reapers team track.",
  },
  {
    id: 'life_skills',
    name: 'Life Skills',
    desc: 'Bank 1 Million Skill Points in Sierra Nueva.',
    tier: 'silver',
    category: 'Rally Adventure',
    guide: 'Accumulate and bank 1,000,000 Skill Points total while in Sierra Nueva. Build long skill chains during free roam — drifting, near misses, and off-road driving generate lots of points. Bank the chain before crashing.',
  },

  // ── Hide & Seek DLC (10) ──

  {
    id: 'hider_and_seeker',
    name: 'Hider and Seeker',
    desc: 'Complete a match of Hide and Seek as both the Hider and the Seeker.',
    tier: 'bronze',
    category: 'Hide & Seek',
    guide: 'Complete one match as a Hider and one match as a Seeker in Hide and Seek. The role is assigned at the start of each match.',
  },
  {
    id: 'bounty_hunter',
    name: 'Bounty Hunter',
    desc: 'Complete 25 matches of Hide and Seek as a Seeker.',
    tier: 'silver',
    category: 'Hide & Seek',
    guide: 'Complete 25 Hide and Seek matches as a Seeker. Seekers chase Hiders and try to identify and tag them before time runs out.',
  },
  {
    id: 'the_hidden',
    name: 'The Hidden',
    desc: 'Complete 5 matches of Hide and Seek as a Hider.',
    tier: 'bronze',
    category: 'Hide & Seek',
    guide: 'Complete 5 Hide and Seek matches as a Hider. Hiders must blend in with traffic and avoid being tagged by Seekers.',
  },
  {
    id: 'dedicated_to_the_cause',
    name: 'Dedicated to the Cause',
    desc: 'Reach a Streak of 20 in Hide and Seek.',
    tier: 'silver',
    category: 'Hide & Seek',
    guide: 'Maintain a streak of 20 consecutive successful outcomes in Hide and Seek. A streak is built by winning as Hider (surviving) or Seeker (tagging correctly) across consecutive matches.',
  },
  {
    id: 'never_back_down',
    name: 'Never Back Down',
    desc: 'Reach a Streak of 50 in Hide and Seek.',
    tier: 'gold',
    category: 'Hide & Seek',
    guide: 'Reach a 50-match winning streak in Hide and Seek. This requires consistent success across many consecutive sessions.',
  },
  {
    id: 'lay_of_the_land',
    name: 'Lay of The Land',
    desc: 'Complete a match in every arena in Hide and Seek.',
    tier: 'silver',
    category: 'Hide & Seek',
    guide: 'Play and complete a Hide and Seek match in every available arena. Arena selection may be random — keep playing until all are covered.',
  },
  {
    id: 'blending_in',
    name: 'Blending In',
    desc: 'Win as a Hider in Hide and Seek.',
    tier: 'bronze',
    category: 'Hide & Seek',
    guide: 'Successfully survive a full match as a Hider without being identified and tagged by Seekers. Blend with traffic, avoid suspicious behaviour, and use the environment to stay hidden.',
  },
  {
    id: 'the_big_reveal',
    name: 'The Big Reveal',
    desc: 'Win as a Seeker in Hide and Seek.',
    tier: 'bronze',
    category: 'Hide & Seek',
    guide: 'Win a match as a Seeker by correctly identifying and tagging enough Hiders. Look for cars driving strangely, avoiding traffic, or clearly trying to hide.',
  },
  {
    id: 'covering_ground',
    name: 'Covering Ground',
    desc: 'Drive 50 miles in Hide and Seek.',
    tier: 'bronze',
    category: 'Hide & Seek',
    guide: 'Drive a cumulative total of 50 miles across all Hide and Seek matches. This will come naturally over time as you play more matches.',
  },
  {
    id: 'catching_a_break',
    name: 'Catching a Break',
    desc: 'Successfully hit a total of 20 Seekers with Chase Breaker in a game of Hide and Seek.',
    tier: 'silver',
    category: 'Hide & Seek',
    guide: 'As a Hider, use the Chase Breaker ability (an EMP-like tool) and successfully hit 20 different Seekers across all your matches. Activate it when Seekers are close.',
  },

  // ── Horizon Realms DLC (17) ──

  {
    id: 'enter_the_realm',
    name: 'Enter the Realm',
    desc: 'Enter any Realm in either Free Mode or Skill Mode.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Access the Horizon Realms DLC from the menu and enter any Realm for the first time. Realms are unique themed environments (Ice Rink, Stunt Park, Oval Track, etc.).',
  },
  {
    id: 'master_of_realms',
    name: 'Master of Realms',
    desc: 'Complete Skill Mode in every Realm.',
    tier: 'gold',
    category: 'Horizon Realms',
    guide: 'Complete Skill Mode in all available Realms. Skill Mode requires earning a target number of Skill Points within a time limit in each themed Realm.',
  },
  {
    id: 'stunt_tacular',
    name: 'Stunt-tacular',
    desc: 'Complete Skill Mode in the Stunt Park whilst driving any Hoonigan.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Stunt Park Realm and complete Skill Mode while driving any Hoonigan-branded car. Hoonigan cars are available in the Autoshow.',
  },
  {
    id: 'youre_on_thin_ice',
    name: "You're On Thin Ice",
    desc: 'Complete Skill Mode in the Ice Rink whilst driving the 2015 Volvo V60 Polestar.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Ice Rink Realm and complete Skill Mode specifically while driving the 2015 Volvo V60 Polestar.',
  },
  {
    id: 'tidy_little_bow',
    name: 'Tidy Little Bow',
    desc: 'Complete Skill Mode in the Oval Track whilst driving the 2013 KTM X-Bow R.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Oval Track Realm and complete Skill Mode specifically while driving the 2013 KTM X-Bow R.',
  },
  {
    id: 'party_like_its_1987',
    name: "Party Like It's 1987",
    desc: "Complete Skill Mode at the Summer Party whilst driving the 1987 Pontiac Firebird.",
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Summer Party Realm and complete Skill Mode while driving the 1987 Pontiac Firebird.',
  },
  {
    id: 'right_at_home',
    name: 'Right At Home',
    desc: 'Complete Skill Mode at Día de Muertos whilst driving any Nissan.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Día de Muertos Realm and complete Skill Mode while driving any Nissan vehicle.',
  },
  {
    id: 'driving_in_a',
    name: 'Driving in a...',
    desc: 'Complete Skill Mode in the Winter Wonderland whilst driving any Lotus.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Winter Wonderland Realm and complete Skill Mode while driving any Lotus vehicle.',
  },
  {
    id: 'winging_it',
    name: 'Winging It',
    desc: 'Complete Skill Mode in the Lunar Drift Arena whilst driving any Aston Martin.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Lunar Drift Arena Realm and complete Skill Mode while driving any Aston Martin vehicle.',
  },
  {
    id: 'as_the_clock_strikes_midnight',
    name: 'As The Clock Strikes Midnight',
    desc: 'Complete Skill Mode at the Neon Airstrip whilst driving any Aventador.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Neon Airstrip Realm and complete Skill Mode while driving any Lamborghini Aventador.',
  },
  {
    id: 'you_might_need_a_map',
    name: 'You Might Need a Map',
    desc: 'Drive a total of 20 miles at the Stadium Maze in Horizon Realms.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'Enter the Stadium Maze Realm and drive a cumulative total of 20 miles within it across any number of sessions.',
  },
  {
    id: 'time_wyrm',
    name: 'Time-Wyrm',
    desc: 'Maintain a speed of 88mph or above for 1 minute at the Lunar Drift Arena in Horizon Realms.',
    tier: 'bronze',
    category: 'Horizon Realms',
    guide: 'In the Lunar Drift Arena Realm, maintain a speed of at least 88mph (141km/h) continuously for one full minute. Use a high-speed car and the longest straight section of the arena.',
  },
  {
    id: 'free_bird',
    name: 'Free Bird',
    desc: 'Earn 100 Speed Skills in Free Mode.',
    tier: 'silver',
    category: 'Horizon Realms',
    guide: 'Earn 100 Speed Skills while playing in Free Mode within Horizon Realms. Speed Skills are earned by driving fast — look for long straights and open spaces in the Realms.',
  },
  {
    id: 'keep_that_camera_rolling',
    name: 'Keep That Camera Rolling',
    desc: 'Take a photo of 25 different cars in Free Mode.',
    tier: 'silver',
    category: 'Horizon Realms',
    guide: 'In Free Mode within Horizon Realms, photograph 25 different car models. Each car must be unique — bring different cars from your garage or find them in shared Free Mode sessions.',
  },
  {
    id: 'drifting_drifting_drifting',
    name: 'Drifting, Drifting, Drifting',
    desc: 'Earn 150 Drift or E-Drift Skills in Free Mode.',
    tier: 'silver',
    category: 'Horizon Realms',
    guide: 'Earn 150 Drift or E-Drift Skills in Free Mode within Horizon Realms. Use a RWD drift car or an electric car capable of E-Drifts. The Stunt Park or Lunar Drift Arena Realms are ideal.',
  },
  {
    id: 'spanning_generations',
    name: 'Spanning Generations',
    desc: 'Drive a car from every decade around Free Mode.',
    tier: 'silver',
    category: 'Horizon Realms',
    guide: 'In Free Mode within Horizon Realms, drive at least one car from each decade (1960s, 1970s, 1980s, 1990s, 2000s, 2010s, 2020s). Bring a varied selection of cars from your garage.',
  },
  {
    id: 'demolisher',
    name: 'Demolisher',
    desc: 'Earn 200 Wreckage Skills in Free Mode.',
    tier: 'silver',
    category: 'Horizon Realms',
    guide: 'Earn 200 Wreckage Skills in Free Mode within Horizon Realms. Wreckage Skills are earned by smashing through destructible objects. The Stunt Park Realm has the most breakable objects.',
  },

  // ── Multiplayer extras ──

  {
    id: 'leaving_tracks',
    name: 'Leaving Tracks',
    desc: 'Drive 50 miles (80.5km) at the Horizon Test Track.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Accumulate 50 miles of driving while at the Horizon Test Track. Simply drive laps — this can be done AFK with a rubber band on the controller.',
  },
  {
    id: 'maxing_out',
    name: 'Maxing Out',
    desc: 'Maintain a speed of 200mph (321.8km/h) for 10 seconds at the Horizon Test Track.',
    tier: 'bronze',
    category: 'Multiplayer',
    guide: 'Reach 200mph at the Horizon Test Track and hold it for 10 seconds. Use an X-Class or top-tier S2 car. The Test Track has a long straight designed for top-speed runs.',
  },
]
