import type { Achievement } from '../types'

export const CATEGORIES = [
  'Story',
  'Completion',
  'Combat & Skills',
  'Exploration',
  'New Game+',
]

export const achievements: Achievement[] = [
  // ── Story (7) — All hidden/secret ──

  {
    id: 'complete_act1',
    steamName: 'CompleteAct1',
    name: "You're Gonna Need Help",
    desc: "Complete 'Surface Tension'.",
    tier: 'bronze',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks after completing the opening story mission 'Surface Tension', where Peter and Miles fight Sandman together.",
  },
  {
    id: 'defeat_sandman',
    steamName: 'DefeatSandman',
    name: 'A New Suit',
    desc: 'Acquire the black suit.',
    tier: 'bronze',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. The black symbiote suit is acquired by Peter Parker during the main story after defeating Sandman.",
  },
  {
    id: 'defeat_lizard',
    steamName: 'DefeatLizard',
    name: 'Medicine',
    desc: "Complete 'It Chose You'.",
    tier: 'silver',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks after completing the mission 'It Chose You', which involves Peter Parker and Dr. Curt Connors (the Lizard).",
  },
  {
    id: 'defeat_li',
    steamName: 'DefeatLi',
    name: 'The Great Hunt',
    desc: "Complete 'Anything Can Be Broken'.",
    tier: 'silver',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks after completing 'Anything Can Be Broken'. Martin Li (Mr. Negative) returns in Miles' storyline.",
  },
  {
    id: 'defeat_kraven',
    steamName: 'DefeatKraven',
    name: 'Another Way',
    desc: "Complete 'No Escape'.",
    tier: 'bronze',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks after completing 'No Escape'. Kraven the Hunter is defeated during this mission.",
  },
  {
    id: 'veno_mj',
    steamName: 'VenoMJ',
    name: 'Leave Us Alone',
    desc: "Complete 'Don't Be Scared'.",
    tier: 'silver',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks after completing 'Don't Be Scared'. This mission involves MJ and the symbiote.",
  },
  {
    id: 'golden_path',
    steamName: 'GoldenPath',
    name: 'Heal the World',
    desc: 'Finish the main story.',
    tier: 'gold',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks upon completing the final main story mission. Expect the main story to take around 15–20 hours.",
  },

  // ── Completion (21) ──

  {
    id: 'superior',
    steamName: 'CompleteAllDistricts',
    name: 'Superior',
    desc: '100% complete all districts.',
    tier: 'gold',
    category: 'Completion',
    guide: "100% complete every district in New York. Track progress via the in-game map. You need to finish all activities including Symbiote Nests, Hunter Bases, Mysteriums, Tech Stashes, Photo Ops, FNSM Requests, Unidentified Targets, EMF Experiments, and Marko's Memories in every district.",
  },
  {
    id: 'kitted_out',
    steamName: 'AllSuits',
    name: 'Kitted Out',
    desc: 'Purchase all available Suits.',
    tier: 'silver',
    category: 'Completion',
    guide: "Purchase all base game suits for both Peter and Miles. Most suits are unlocked through story progression and completing activities. Use Hero Tokens, City Tokens, and Tech Parts to purchase them from the Suits menu. DLC suits do not count.",
  },
  {
    id: 'to_the_max',
    steamName: 'UpgradeAllGadgets',
    name: 'To the Max',
    desc: 'Purchase all Gadget upgrades.',
    tier: 'silver',
    category: 'Completion',
    guide: "Purchase all upgrades for every gadget for both Peter and Miles. You'll need a large supply of Tech Parts and various tokens. Focus on district completion to earn the resources needed.",
  },
  {
    id: 'fully_loaded',
    steamName: 'AllSuitTech',
    name: 'Fully Loaded',
    desc: 'Purchase all Suit Tech upgrades.',
    tier: 'silver',
    category: 'Completion',
    guide: "Purchase every Suit Tech upgrade from the Skills/Suit Tech menu. These require Hero Tokens earned from completing activities and story missions.",
  },
  {
    id: 'amazing',
    steamName: 'MaxLevel',
    name: 'Amazing',
    desc: 'Reach max level.',
    tier: 'silver',
    category: 'Completion',
    guide: "Reach the maximum level cap. You earn XP from completing story missions, side content, and open world activities. This should come naturally while going for 100% completion.",
  },
  {
    id: 'friendly_neighborhood',
    steamName: 'CompleteAllFNSM',
    name: 'Friendly Neighborhood Spider-Man',
    desc: 'Complete all FNSM App requests.',
    tier: 'silver',
    category: 'Completion',
    guide: "Complete all FNSM (Friendly Neighborhood Spider-Man) App requests that appear throughout the story and open world. These are short side missions requested by citizens and appear as white phone icons on the map.",
  },
  {
    id: 'foundational',
    steamName: 'EmilyMayFoundationQuests',
    name: 'Foundational',
    desc: 'Complete all EMF Experiments.',
    tier: 'silver',
    category: 'Completion',
    guide: "Complete all Emily-May Foundation (EMF) Experiments. These are scientific side activities tied to Harry Osborn's foundation. They appear as green flask icons on the map and involve unique puzzle-based challenges.",
  },
  {
    id: 'grains_of_sand',
    steamName: 'SandmanCollectibles',
    name: 'Grains of Sand',
    desc: "Piece together Sandman's broken memories.",
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Collect all of Marko's Memories (sand mound collectibles) scattered across the map. These become available after the Sandman boss fight early in the game. Use the map to track their locations.",
  },
  {
    id: 'exterminator',
    steamName: 'SymbioteNests',
    name: 'Exterminator',
    desc: 'Complete all Symbiote Nests.',
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Destroy all Symbiote Nests across the city. These appear as purple nest icons on the map after they become available mid-story. Each nest requires you to defeat symbiote enemies and destroy the nest core.",
  },
  {
    id: 'seek_and_destroy',
    steamName: 'HunterBases',
    name: 'Seek and Destroy',
    desc: "Complete all of Kraven's Hunter Bases.",
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Infiltrate and shut down all of Kraven's Hunter Bases. These appear as red base icons on the map after being unlocked mid-story. Each base involves combat encounters with Kraven's hunters.",
  },
  {
    id: 'behind_the_masks',
    steamName: 'CompleteAllMysterioChallenges',
    name: 'Behind the Masks',
    desc: "Complete all Mysteriums (Grand Finale).",
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Complete all Mysterium challenges across the city. These are holographic illusion challenges set up by Mysterio, appearing as orange mask icons. Complete all of them to unlock the 'Grand Finale' mission.",
  },
  {
    id: 'data_collector',
    steamName: 'CompleteAllSpiderBots',
    name: 'Data Collector',
    desc: 'Locate all Unidentified Targets.',
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Complete the 'Target Identified' side content by finding all Unidentified Targets. These appear as question mark icons on the radar when you're nearby. Track them all down across the city.",
  },
  {
    id: 'crimson_hour',
    steamName: 'WraithBoss',
    name: 'Crimson Hour',
    desc: "Complete the Wraith questline.",
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Complete all missions in the Wraith (Yuri Watanabe) questline — 'It Was Meant for Me'. These missions unlock progressively. Follow Yuri's investigations to unlock the full chain.",
  },
  {
    id: 'funky_wireless',
    steamName: 'FalconChases',
    name: 'Funky Wireless Protocols',
    desc: "Solve the mystery of the Spider-Bots' origin.",
    tier: 'bronze',
    category: 'Completion',
    guide: "Track down and investigate the mysterious Spider-Bots appearing across the city. Follow the signal trail until you uncover their origin.",
  },
  {
    id: 'co_signing',
    steamName: 'ProwlerTechStashes',
    name: 'Co-Signing',
    desc: 'Complete all Tech Stashes.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Find and complete all of Miles' Prowler Tech Stashes hidden across the city. These appear as green crate icons on the map after being unlocked.",
  },
  {
    id: 'new_york_new_york',
    steamName: 'AllPhotoLocations',
    name: 'New York, New York',
    desc: 'Complete all Photo Ops.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Photograph all Photo Op locations across the city. These appear as camera icons on the map. Simply approach each location and take a photo using the photo mode prompt.",
  },
  {
    id: 'brooklyn_pride',
    steamName: 'BrooklynVisions',
    name: 'Brooklyn Pride',
    desc: "Complete the Brooklyn Visions mission.",
    tier: 'bronze',
    category: 'Completion',
    guide: "Complete the 'A Gift' mission chain centered around Miles' old school, Brooklyn Visions Academy. This side mission becomes available during the story.",
  },
  {
    id: 'my_community',
    steamName: 'HarlemArc',
    name: 'My Community',
    desc: "Complete the Harlem Cultural Museum mission.",
    tier: 'bronze',
    category: 'Completion',
    guide: "Complete the 'Hard Bop' mission chain tied to the Harlem Cultural Museum. These missions involve Miles reconnecting with his community. They unlock during the story.",
  },
  {
    id: 'a_new_adventure',
    steamName: 'FNSM_Howard',
    name: 'A New Adventure',
    desc: 'Help Howard find his purpose.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Complete the 'Howard' FNSM App request chain. Howard is a recurring character across the Spider-Man games. Find him via the FNSM App and complete his mission chain.",
  },
  {
    id: 'resourceful',
    steamName: 'CollectTechParts',
    name: 'Resourceful',
    desc: 'Collect a total of 10,000 Tech Parts.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Collect 10,000 Tech Parts total. These drop from enemies and are found in chests and Tech Stashes. This should accumulate naturally while completing all side content.",
  },
  {
    id: 'dedicated',
    steamName: 'PlatinumTrophy',
    name: 'Dedicated',
    desc: 'Collect all other achievements.',
    tier: 'gold',
    category: 'Completion',
    guide: "Unlock every other achievement in the game. This is the equivalent of a PlayStation Platinum trophy — the ultimate 100% completion reward.",
  },

  // ── Combat & Skills (6) ──

  {
    id: 'evolved',
    steamName: 'BlueVenomKills',
    name: 'Evolved',
    desc: 'Defeat 100 enemies with Evolved Venom abilities.',
    tier: 'silver',
    category: 'Combat & Skills',
    secret: true,
    guide: "Defeat 100 enemies using Miles Morales' bio-electric Venom abilities (blue lightning attacks). These include Venom Strike, Venom Jump, Venom Dash, and Chain Lightning. Use them consistently in combat throughout the game.",
  },
  {
    id: 'armed_and_dangerous',
    steamName: 'IronArmKills',
    name: 'Armed and Dangerous',
    desc: 'Defeat 100 enemies with Spider-Arm abilities.',
    tier: 'silver',
    category: 'Combat & Skills',
    secret: true,
    guide: "Defeat 100 enemies using Peter Parker's Spider-Arm abilities. These are the mechanical appendages that emerge from the symbiote suit. Use them frequently during combat encounters as Peter.",
  },
  {
    id: 'venom_overload',
    steamName: 'VenomModeKills',
    name: 'Venom Overload',
    desc: "Defeat enemies using the black suit's symbiote powers.",
    tier: 'bronze',
    category: 'Combat & Skills',
    secret: true,
    guide: "Defeat enemies while Peter Parker is in the full symbiote-enhanced state. Use the black suit's Venom mode attacks against enemy groups. This accumulates across all combat encounters where the symbiote abilities are active.",
  },
  {
    id: 'surge',
    steamName: 'SymbiotePowersDuringRageMode',
    name: 'Surge',
    desc: 'Use Symbiote Abilities 25 times during Symbiote Surge.',
    tier: 'silver',
    category: 'Combat & Skills',
    secret: true,
    guide: "Activate Peter's Symbiote Surge (the black suit's overdrive state) and use Symbiote Abilities 25 times while it's active. Symbiote Surge is triggered by filling the Surge meter in combat.",
  },
  {
    id: 'overdrive',
    steamName: 'ReverseFluxTargetCount',
    name: 'Overdrive',
    desc: 'Use Reverse Flux to pull 6 or more enemies simultaneously.',
    tier: 'bronze',
    category: 'Combat & Skills',
    secret: true,
    guide: "As Miles, use Reverse Flux (a bio-electric ability that pulls enemies inward) while 6 or more enemies are within range. Set this up by finding a large group of enemies — enemy bases and Symbiote Nests are ideal spots.",
  },
  {
    id: 'antidote',
    steamName: 'AntiVenomSymbioteKill',
    name: 'Antidote',
    desc: 'Defeat a Symbiote enemy under Anti-Venom status effect.',
    tier: 'bronze',
    category: 'Combat & Skills',
    secret: true,
    guide: "Apply the Anti-Venom status effect to a Symbiote enemy, then defeat them while it's active. Anti-Venom abilities unlock for Miles later in the story and are effective against symbiote-infected enemies.",
  },

  // ── Exploration (6) ──

  {
    id: 'slack_line',
    steamName: 'WebLineTakedowns',
    name: 'Slack Line',
    desc: 'Perform 25 stealth takedowns from the Web Line.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Create a Web Line (a horizontal web stretched between two surfaces) and perform stealth takedowns on enemies standing below or near it. Do this 25 times total across all encounters. The Web Line ability must be equipped.",
  },
  {
    id: 'hang_ten',
    steamName: 'AirTricksInARow',
    name: 'Hang Ten',
    desc: 'Perform 30 Air Tricks in a row without touching the ground.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "While in the air, perform 30 different tricks in succession without landing. Jump from the top of a very tall skyscraper (like one of the Financial District towers) and chain trick inputs continuously as you fall. Gadget/web assists can extend your airtime.",
  },
  {
    id: 'stylish',
    steamName: 'EquipSuitVariant',
    name: 'Stylish',
    desc: 'Equip a suit style.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Open the Suits menu and equip any suit style (color variant). Most suits have multiple color styles available. Simply select one to unlock this achievement.",
  },
  {
    id: 'splat',
    steamName: 'FailAirTrick',
    name: 'Splat',
    desc: 'Attempt a trick right before hitting the ground.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Attempt a trick input right as you're about to hit the ground — too late to complete it — resulting in a crash landing. Jump from a low height, wait until the very last moment, then trigger a trick. You should faceplant for the achievement to pop.",
  },
  {
    id: 'you_know_what_to_do',
    steamName: 'VisitMayGrave',
    name: 'You Know What to Do',
    desc: "Visit Aunt May's grave.",
    tier: 'bronze',
    category: 'Exploration',
    guide: "As Peter Parker, visit Aunt May's grave in the cemetery. Use the map to find the cemetery in the Upper West Side area. Peter will have a quiet moment of reflection.",
  },
  {
    id: 'home_run',
    steamName: 'ConeyIslandHomeRun',
    name: 'Home Run!',
    desc: 'Round all the bases at the Coney Island stadium.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Visit the Coney Island baseball stadium in Queens and interact with each base in order — first, second, third, then home plate. A prompt will appear as you approach each base.",
  },
  {
    id: 'just_let_go',
    steamName: 'FindMilesAndPhinTrophy',
    name: 'Just Let Go',
    desc: "Find the science trophy Miles and Phin won together.",
    tier: 'bronze',
    category: 'Exploration',
    guide: "As Miles, find the science competition trophy he and Phin Mason won together. Use the map to find the memorial location in Harlem. Miles will have a reflective moment thinking about his late friend.",
  },
  {
    id: 'soar',
    steamName: 'WingsuitConeyIslandToQueens',
    name: 'Soar',
    desc: 'Glide from Coney Island to Queens using only Web Wings.',
    tier: 'bronze',
    category: 'Exploration',
    guide: "Starting from Coney Island (the southernmost tip of the map), deploy your Web Wings and glide all the way to Queens without web-swinging. Find a high perch, catch thermal updrafts to gain altitude, and ride the wind to cover the distance.",
  },

  // ── New Game+ (1) ──

  {
    id: 'once_more_with_feeling',
    steamName: 'NewGamePlusComplete',
    name: 'Once More, With Feeling',
    desc: 'Finish the main story in New Game+ mode.',
    tier: 'bronze',
    category: 'New Game+',
    guide: "Complete the main story a second time using New Game+. After finishing the game, start a New Game+ from the save selection screen. You keep all your suits, upgrades, and abilities. Only main story missions (marked in yellow) are required — expect the run to take around 6–8 hours.",
  },
]
