import type { Achievement } from '../types'

export const CATEGORIES = [
  'Story',
  'Completion',
  'Combat & Skills',
  'Exploration',
  'New Game+',
]

export const achievements: Achievement[] = [
  // ── Story (8) — All hidden/secret ──

  {
    id: 'youre_gonna_need_help',
    name: "You're Gonna Need Help",
    desc: 'Get some help with an old enemy.',
    tier: 'bronze',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks during the opening mission 'Surface Tension' where Peter and Miles team up to fight Sandman.",
  },
  {
    id: 'a_new_suit',
    name: 'A New Suit',
    desc: 'Acquire the black suit.',
    tier: 'bronze',
    category: 'Story',
    secret: true,
    guide: 'Story related, cannot be missed. Peter acquires the black symbiote suit during the main story.',
  },
  {
    id: 'medicine',
    name: 'Medicine',
    desc: 'Help an old friend.',
    tier: 'silver',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks after completing the 'It Chose You' mission involving Dr. Curt Connors.",
  },
  {
    id: 'another_way',
    name: 'Another Way',
    desc: 'Find another way.',
    tier: 'bronze',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks during Miles' storyline involving Martin Li (Mr. Negative).",
  },
  {
    id: 'the_great_hunt',
    name: 'The Great Hunt',
    desc: 'End the hunt.',
    tier: 'silver',
    category: 'Story',
    secret: true,
    guide: 'Story related, cannot be missed. Unlocks after defeating Kraven the Hunter during the main story.',
  },
  {
    id: 'leave_us_alone',
    name: 'Leave Us Alone',
    desc: 'Protect what matters most.',
    tier: 'silver',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks during the symbiote storyline climax involving Peter, Harry, and the Venom symbiote.",
  },
  {
    id: 'i_quit',
    name: 'I Quit',
    desc: 'Make a difficult choice.',
    tier: 'bronze',
    category: 'Story',
    secret: true,
    guide: "Story related, cannot be missed. Unlocks during a pivotal story moment involving Mary Jane and the symbiote.",
  },
  {
    id: 'heal_the_world',
    name: 'Heal the World',
    desc: 'Finish the main story.',
    tier: 'gold',
    category: 'Story',
    secret: true,
    guide: 'Story related, cannot be missed. Unlocks upon completing the final main story mission. The main story takes approximately 15–20 hours.',
  },

  // ── Completion (21) ──

  {
    id: 'superior',
    name: 'Superior',
    desc: '100% complete all districts.',
    tier: 'gold',
    category: 'Completion',
    guide: "100% complete every district in New York. Track progress via the in-game map. You need to finish all Symbiote Nests, Hunter Bases, Mysteriums, Tech Stashes, Photo Ops, FNSM Requests, EMF Experiments, and Marko's Memories in every district.",
  },
  {
    id: 'kitted_out',
    name: 'Kitted Out',
    desc: 'Purchase all available Suits.',
    tier: 'silver',
    category: 'Completion',
    guide: 'Purchase all base game suits for both Peter and Miles. Most suits are unlocked through story progression and activities. Use Hero Tokens, City Tokens, and Tech Parts to purchase them from the Suits menu. DLC suits do not count.',
  },
  {
    id: 'to_the_max',
    name: 'To the Max',
    desc: 'Purchase all Gadget upgrades.',
    tier: 'silver',
    category: 'Completion',
    guide: "Purchase all upgrades for every gadget for both Peter and Miles. You'll need a large supply of Tech Parts and tokens — focus on district completion to earn the resources needed.",
  },
  {
    id: 'fully_loaded',
    name: 'Fully Loaded',
    desc: 'Purchase all Suit Tech upgrades.',
    tier: 'silver',
    category: 'Completion',
    guide: 'Purchase every Suit Tech upgrade from the Skills menu. These require Hero Tokens earned from completing activities and story missions.',
  },
  {
    id: 'amazing',
    name: 'Amazing',
    desc: 'Reach max level.',
    tier: 'silver',
    category: 'Completion',
    guide: 'Reach the maximum level cap. XP is earned from story missions, side content, and open world activities. This comes naturally while going for 100% completion.',
  },
  {
    id: 'friendly_neighborhood',
    name: 'Friendly Neighborhood Spider-Man',
    desc: 'Complete all FNSM App requests.',
    tier: 'silver',
    category: 'Completion',
    guide: 'Complete all FNSM (Friendly Neighborhood Spider-Man) App requests. These are short side missions requested by citizens, appearing as white phone icons on the map.',
  },
  {
    id: 'foundational',
    name: 'Foundational',
    desc: 'Complete all EMF Experiments.',
    tier: 'silver',
    category: 'Completion',
    guide: "Complete all Emily-May Foundation (EMF) Experiments. These are scientific side activities tied to Harry Osborn's foundation, appearing as green flask icons on the map.",
  },
  {
    id: 'grains_of_sand',
    name: 'Grains of Sand',
    desc: "Piece together Sandman's broken memories.",
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Collect all of Marko's Memories (sand mound collectibles) scattered across the map. These become available after the Sandman boss fight early in the game.",
  },
  {
    id: 'exterminator',
    name: 'Exterminator',
    desc: 'Complete all Symbiote Nests.',
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: 'Destroy all Symbiote Nests across the city. These appear as purple nest icons on the map after they become available mid-story. Each nest requires defeating symbiote enemies and destroying the nest core.',
  },
  {
    id: 'seek_and_destroy',
    name: 'Seek and Destroy',
    desc: "Complete all of Kraven's Hunter Bases.",
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Infiltrate and shut down all of Kraven's Hunter Bases. These appear as red base icons on the map after being unlocked mid-story.",
  },
  {
    id: 'behind_the_masks',
    name: 'Behind the Masks',
    desc: 'Complete all Mysteriums.',
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Complete all Mysterium challenges (Grand Finale) across the city. These are holographic illusion challenges set up by Mysterio, appearing as orange mask icons on the map.",
  },
  {
    id: 'data_collector',
    name: 'Data Collector',
    desc: 'Locate all Unidentified Targets.',
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Complete the 'Target Identified' side content by finding all Unidentified Targets. These appear as question mark icons on the radar when you're nearby.",
  },
  {
    id: 'crimson_hour',
    name: 'Crimson Hour',
    desc: 'Complete the Wraith questline.',
    tier: 'silver',
    category: 'Completion',
    secret: true,
    guide: "Complete all missions in the Wraith (Yuri Watanabe) questline — 'It Was Meant for Me'. Follow Yuri's investigations across the city to unlock the full chain.",
  },
  {
    id: 'funky_wireless',
    name: 'Funky Wireless Protocols',
    desc: "Solve the mystery of the Spider-Bots' origin.",
    tier: 'bronze',
    category: 'Completion',
    guide: "Investigate and find the origin of the mysterious Spider-Bots appearing across the city. Track down all Spider-Bots to uncover the mystery.",
  },
  {
    id: 'co_signing',
    name: 'Co-Signing',
    desc: 'Complete all Tech Stashes.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Find and complete all of Miles' Prowler Tech Stashes hidden across the city. These appear as green crate icons on the map.",
  },
  {
    id: 'new_york_new_york',
    name: 'New York, New York',
    desc: 'Complete all Photo Ops.',
    tier: 'bronze',
    category: 'Completion',
    guide: 'Photograph all Photo Op locations across the city. These appear as camera icons on the map. Approach each location and take a photo using the photo mode prompt.',
  },
  {
    id: 'brooklyn_pride',
    name: 'Brooklyn Pride',
    desc: 'Complete the Brooklyn Visions mission.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Complete the 'A Gift' mission chain centered around Miles' old school, Brooklyn Visions Academy. This side mission becomes available during the story.",
  },
  {
    id: 'my_community',
    name: 'My Community',
    desc: 'Complete the Harlem Cultural Museum mission.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Complete the 'Hard Bop' mission chain tied to the Harlem Cultural Museum. These missions involve Miles reconnecting with his community and unlock during the story.",
  },
  {
    id: 'a_new_adventure',
    name: 'A New Adventure',
    desc: 'Help Howard find his purpose.',
    tier: 'bronze',
    category: 'Completion',
    guide: "Complete the 'Howard' FNSM App request chain. Howard is a recurring character across the Spider-Man games — find him via the FNSM App and complete his mission chain.",
  },
  {
    id: 'resourceful',
    name: 'Resourceful',
    desc: 'Collect a total of 10,000 Tech Parts.',
    tier: 'bronze',
    category: 'Completion',
    guide: 'Collect 10,000 Tech Parts total. These drop from enemies and are found in crates and Tech Stashes. This accumulates naturally while completing all side content.',
  },
  {
    id: 'dedicated',
    name: 'Dedicated',
    desc: 'Collect all other achievements.',
    tier: 'gold',
    category: 'Completion',
    guide: "Unlock every other achievement in the game. This is equivalent to a PlayStation Platinum trophy — the ultimate 100% completion reward.",
  },

  // ── Combat & Skills (6) ──

  {
    id: 'evolved',
    name: 'Evolved',
    desc: "Defeat 100 enemies with Miles' Venom abilities.",
    tier: 'silver',
    category: 'Combat & Skills',
    secret: true,
    guide: "Defeat 100 enemies using Miles Morales' bio-electric Venom abilities (blue lightning attacks). These include Venom Strike, Venom Jump, Venom Dash, and Chain Lightning. Use them consistently throughout the game.",
  },
  {
    id: 'armed_and_dangerous',
    name: 'Armed and Dangerous',
    desc: "Defeat 100 enemies with Peter's Spider-Arm abilities.",
    tier: 'silver',
    category: 'Combat & Skills',
    secret: true,
    guide: "Defeat 100 enemies using Peter Parker's Spider-Arm abilities. These are the mechanical appendages that emerge during combat. Use them frequently as Peter throughout the game.",
  },
  {
    id: 'surge',
    name: 'Surge',
    desc: 'Use Symbiote Abilities 25 times during Symbiote Surge.',
    tier: 'silver',
    category: 'Combat & Skills',
    secret: true,
    guide: "Activate Peter's Symbiote Surge (the black suit's overdrive state) and use Symbiote Abilities 25 times while it's active. Symbiote Surge is triggered by filling the Surge meter in combat.",
  },
  {
    id: 'overdrive',
    name: 'Overdrive',
    desc: 'Use Reverse Flux to pull 6 or more enemies simultaneously.',
    tier: 'bronze',
    category: 'Combat & Skills',
    secret: true,
    guide: "As Miles, use Reverse Flux (a bio-electric ability that pulls enemies inward) while 6 or more enemies are within range. Enemy bases and Symbiote Nests are the best spots for large groups.",
  },
  {
    id: 'antidote',
    name: 'Antidote',
    desc: 'Defeat a Symbiote enemy under Anti-Venom status effect.',
    tier: 'bronze',
    category: 'Combat & Skills',
    secret: true,
    guide: "Apply the Anti-Venom status effect to a Symbiote enemy then defeat them while it's active. Anti-Venom abilities unlock for Miles later in the story and are especially effective against symbiote-infected enemies.",
  },
  {
    id: 'slack_line',
    name: 'Slack Line',
    desc: 'Perform 25 stealth takedowns from the Web Line.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: "Create a Web Line (a horizontal web stretched between two surfaces) and perform stealth takedowns on enemies below or near it. Do this 25 times total across all encounters.",
  },

  // ── Exploration (7) ──

  {
    id: 'hang_ten',
    name: 'Hang Ten',
    desc: 'Perform 30 Air Tricks in a row without touching the ground.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'While airborne, perform 30 different tricks in succession without landing. Jump from the top of a tall skyscraper and chain trick inputs continuously as you fall. Web assists can extend your airtime.',
  },
  {
    id: 'stylish',
    name: 'Stylish',
    desc: 'Equip a suit style.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'Open the Suits menu and equip any suit style (color variant). Most suits have multiple color styles available — simply select one.',
  },
  {
    id: 'splat',
    name: 'Splat',
    desc: 'Attempt a trick right before hitting the ground.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'Attempt a trick input right as you are about to hit the ground — too late to complete it — resulting in a crash landing. Jump from a low height, wait until the very last moment, then trigger a trick input.',
  },
  {
    id: 'you_know_what_to_do',
    name: 'You Know What to Do',
    desc: "Visit Aunt May's grave.",
    tier: 'bronze',
    category: 'Exploration',
    guide: "As Peter Parker, visit Aunt May's grave in the cemetery. Peter will have a quiet moment of reflection.",
  },
  {
    id: 'home_run',
    name: 'Home Run!',
    desc: 'Round all the bases at the Coney Island stadium.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'Visit the Coney Island baseball stadium in Queens and interact with each base in order — first, second, third, then home plate. A prompt will appear at each base.',
  },
  {
    id: 'just_let_go',
    name: 'Just Let Go',
    desc: "Find the science trophy Miles and Phin won together.",
    tier: 'bronze',
    category: 'Exploration',
    guide: "As Miles, find the science competition trophy he and Phin Mason won together. Located in Harlem — Miles will have a reflective moment thinking about his late friend.",
  },
  {
    id: 'soar',
    name: 'Soar',
    desc: 'Glide from Coney Island to Queens using only Web Wings.',
    tier: 'bronze',
    category: 'Exploration',
    guide: 'Starting from Coney Island (the southernmost tip of the map), deploy your Web Wings and glide all the way to Queens without web-swinging. Find a high perch, catch thermal updrafts to gain altitude, and ride the wind the whole way.',
  },

  // ── New Game+ (1) ──

  {
    id: 'once_more_with_feeling',
    name: 'Once More, With Feeling',
    desc: 'Finish the main story in New Game+ mode.',
    tier: 'bronze',
    category: 'New Game+',
    guide: "Complete the main story a second time on New Game+. After finishing the game, start New Game+ from the save selection screen — you keep all suits, upgrades, and abilities. Only main story missions are required; expect around 6–8 hours.",
  },
]
