import type { Achievement } from '../types'

export const CATEGORIES = [
  'Story & Endings',
  'Romances & Companions',
  'Side Quests & Activities',
  'Combat & Skills',
  'Exploration & Collectibles',
  'Phantom Liberty',
]

export const achievements: Achievement[] = [

  // ── Story & Endings (10) ──

  {
    id: 'the_fool',
    name: 'The Fool',
    desc: 'Become a mercenary.',
    tier: 'bronze',
    category: 'Story & Endings',
    secret: true,
    guide: 'Story related, cannot be missed. Unlocks early in the prologue as V begins their life as a mercenary in Night City.',
  },
  {
    id: 'the_lovers',
    name: 'The Lovers',
    desc: 'Steal the Relic.',
    tier: 'bronze',
    category: 'Story & Endings',
    secret: true,
    guide: 'Story related, cannot be missed. Unlocks during the heist mission "The Pickup / The Heist" when V and Jackie steal the Relic from Konpeki Plaza.',
  },
  {
    id: 'the_hermit',
    name: 'The Hermit',
    desc: 'Find Alt Cunningham.',
    tier: 'bronze',
    category: 'Story & Endings',
    secret: true,
    guide: 'Story related, cannot be missed. Unlocks during the main quest "Transmission" when V makes contact with Alt Cunningham in cyberspace.',
  },
  {
    id: 'the_wheel_of_fortune',
    name: 'The Wheel of Fortune',
    desc: 'Interrogate Anders Hellman.',
    tier: 'bronze',
    category: 'Story & Endings',
    secret: true,
    guide: 'Story related, cannot be missed. Unlocks during the main quest "Life During Wartime" when V tracks down Arasaka engineer Anders Hellman.',
  },
  {
    id: 'the_high_priestess',
    name: 'The High Priestess',
    desc: 'Talk with Hanako Arasaka.',
    tier: 'bronze',
    category: 'Story & Endings',
    secret: true,
    guide: 'Story related, cannot be missed. Unlocks during the main quest "Tapeworm / Transmission" when V finally meets Hanako Arasaka at Embers.',
  },
  {
    id: 'the_world',
    name: 'The World',
    desc: 'Complete the main storyline.',
    tier: 'gold',
    category: 'Story & Endings',
    guide: 'Complete any of the main game endings. This unlocks regardless of which ending path you choose for the final mission.',
  },
  {
    id: 'the_devil',
    name: 'The Devil',
    desc: 'Help Takemura avenge Saburo.',
    tier: 'gold',
    category: 'Story & Endings',
    secret: true,
    guide: '⚠️ Missable. During "Search and Destroy," save Takemura when he is pinned down — do NOT leave without him. Then in the finale, choose to go with Hanako Arasaka and side with Arasaka to unlock this ending.',
  },
  {
    id: 'the_star',
    name: 'The Star',
    desc: 'Leave Night City with the Aldecaldos.',
    tier: 'gold',
    category: 'Story & Endings',
    secret: true,
    guide: 'Complete all of Panam Palmer\'s quests. In the finale, call Panam and choose to leave Night City with the Aldecaldos. This unlocks the "All Along the Watchtower" ending.',
  },
  {
    id: 'the_sun',
    name: 'The Sun',
    desc: 'Become a Night City legend.',
    tier: 'gold',
    category: 'Story & Endings',
    secret: true,
    guide: 'Complete Rogue\'s questline (requires completing Chippin\' In and Blistering Love side jobs). In the finale, call Rogue and choose to storm Arasaka Tower together to unlock the "Path of Glory" ending.',
  },
  {
    id: 'temperance',
    name: 'Temperance',
    desc: 'Let Johnny keep your body.',
    tier: 'gold',
    category: 'Story & Endings',
    secret: true,
    guide: 'After completing the main quest, when given the choice at the rooftop, give your body to Johnny Silverhand. This unlocks the "New Dawn Fades" ending where Johnny carries on in V\'s place.',
  },

  // ── Romances & Companions (5) ──

  {
    id: 'to_protect_and_serve',
    name: 'To Protect and Serve',
    desc: 'Complete River Ward\'s questline.',
    tier: 'silver',
    category: 'Romances & Companions',
    secret: true,
    guide: 'Complete all of River Ward\'s side quests starting with "I Fought the Law." Follow through "The Hunt" and "Following the River" to their conclusion. River is available after Act 2 begins.',
  },
  {
    id: 'to_bad_decisions',
    name: 'To Bad Decisions!',
    desc: 'Complete Kerry Eurodyne\'s questline.',
    tier: 'silver',
    category: 'Romances & Companions',
    secret: true,
    guide: '⚠️ Missable. Requires completing Rogue\'s quests first (Chippin\' In, Blistering Love). Kerry\'s quests then unlock: "I\'ll Fly Away," "Rebel! Rebel!," "A Like Supreme," and "Off the Leash." Complete them all.',
  },
  {
    id: 'judy_vs_night_city',
    name: 'Judy vs Night City',
    desc: 'Complete Judy Alvarez\'s questline.',
    tier: 'silver',
    category: 'Romances & Companions',
    secret: true,
    guide: 'Complete all of Judy\'s side quests: "Both Sides, Now," "Ex-Factor," "Talkin\' \'Bout a Revolution," "Pisces," and "Pyramid Song." These unlock progressively through Acts 2 and 3.',
  },
  {
    id: 'life_of_the_road',
    name: 'Life of the Road',
    desc: 'Complete Panam Palmer\'s questline.',
    tier: 'silver',
    category: 'Romances & Companions',
    secret: true,
    guide: 'Complete all of Panam\'s side quests: "Riders on the Storm," "With a Little Help from My Friends," "Queen of the Highway." These unlock after meeting her during the main quest "Ghost Town."',
  },
  {
    id: 'bushido_and_chill',
    name: 'Bushido and Chill',
    desc: 'Complete Rogue\'s questline.',
    tier: 'silver',
    category: 'Romances & Companions',
    secret: true,
    guide: '⚠️ Missable. Complete "Chippin\' In" and "Blistering Love" with Rogue. During "Chippin\' In," when visiting Johnny\'s grave, choose the dialogue option that involves giving Johnny a chance — being hostile to Johnny locks you out.',
  },

  // ── Side Quests & Activities (4) ──

  {
    id: 'breathtaking',
    name: 'Breathtaking',
    desc: 'Collect all items that once belonged to Johnny Silverhand.',
    tier: 'gold',
    category: 'Side Quests & Activities',
    guide: '⚠️ Missable. Collect all 7 of Johnny\'s iconic items: Aviator Sunglasses, Jacket, Pants, Shoes, Samurai Bandana, Malorian Arms 3516 pistol, and the Porsche 911. Most are story-given; the Porsche is from the gig "Psychofan" in Vista del Rey — do this before Act 3 ends.',
  },
  {
    id: 'i_am_the_law',
    name: 'I Am The Law',
    desc: 'Complete all Cyberpsycho Sightings.',
    tier: 'silver',
    category: 'Side Quests & Activities',
    guide: 'Find and neutralise all 17 Cyberpsychos across Night City. These are marked as NCPD Scanner Hustles with a distinct icon. Regina Jones will call you about each one — V\'s task is to subdue them non-lethally where possible.',
  },
  {
    id: 'legend_of_the_afterlife',
    name: 'Legend of The Afterlife',
    desc: 'Reach max Street Cred.',
    tier: 'silver',
    category: 'Side Quests & Activities',
    guide: 'Reach Street Cred level 50. Earn Street Cred by completing gigs, NCPD hustles, and side quests. The easiest way is to clear all gigs across the city — you will likely hit level 50 naturally while going for the district completion achievements.',
  },
  {
    id: 'the_wandering_fool',
    name: 'The Wandering Fool',
    desc: 'Find all the tarot graffiti for the job Fool on the Hill.',
    tier: 'silver',
    category: 'Side Quests & Activities',
    guide: 'Accept the side job "Fool on the Hill" from Misty\'s Esoterica rooftop after completing "The Heist." Find all 20 tarot card graffiti locations spread across Night City. Use a guide map — many are hidden on walls and rooftops.',
  },

  // ── Combat & Skills (17) ──

  {
    id: 'full_body_conversion',
    name: 'Full Body Conversion',
    desc: 'Install at least one implant in each system and body part.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Visit any Ripperdoc and install at least one cyberware implant in every slot: Frontal Cortex, Ocular System, Circulatory System, Immune System, Nervous System, Integumentary System, Operating System, Arms, Legs, and Skeleton.',
  },
  {
    id: 'gun_fu',
    name: 'Gun Fu',
    desc: 'Kill or incapacitate 3 enemies in quick succession with a revolver or pistol in close combat.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Kill 3 enemies within 3.5 seconds using a pistol or revolver while within 5 meters of them. Find a group of 3+ enemies, get close, and shoot quickly. Easier on normal difficulty — try gigs or enemy camps in the Badlands.',
  },
  {
    id: 'christmas_tree_attack',
    name: 'Christmas Tree Attack',
    desc: 'Complete a Breach Protocol with a minimum of 3 daemons uploaded.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Level up your Intelligence attribute and invest in Breach Protocol perks to extend the code matrix. Select a sequence path that uploads 3 or more daemons simultaneously. Easier on less-defended targets like access points.',
  },
  {
    id: 'ten_out_of_ten',
    name: 'Ten out of Ten',
    desc: 'Reach the max level in any skill.',
    tier: 'silver',
    category: 'Combat & Skills',
    guide: '⚠️ Missable in a sense — skill XP is earned by doing. Pick one combat style early and stick with it. Max level is 20 for any skill (Handguns, Blades, Athletics, etc.). Handguns or Stealth are easiest to grind naturally.',
  },
  {
    id: 'gunslinger',
    name: 'Gunslinger',
    desc: 'Shoot an enemy grenade in midair with a revolver.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Equip a revolver and wait for an enemy to throw a grenade. Shoot the grenade while it is airborne. Easier to set up in a fight with multiple enemies. Enemies in Maelstrom and Valentinos territory tend to use grenades frequently.',
  },
  {
    id: 'two_heads_one_bullet',
    name: 'Two Heads, One Bullet',
    desc: 'Kill or incapacitate 2 enemies with the same sniper rifle shot.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Find two enemies standing in a line and shoot through both with a sniper rifle. Works best with a powerful sniper that has high penetration. Line up shots carefully — try enemy camps where guards patrol close together.',
  },
  {
    id: 'rough_landing',
    name: 'Rough Landing',
    desc: 'While Berserk cyberware is active, perform a Superhero Landing to kill or incapacitate 2 enemies.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Equip Berserk Operating System cyberware (available from Ripperdocs). Activate Berserk, climb to a height above 2 grouped enemies, then press the crouch button while falling to perform a Superhero Landing. Both enemies must be in the landing radius.',
  },
  {
    id: 'stanislavskis_method',
    name: 'Stanislavski\'s Method',
    desc: 'Use a dialogue option related to V\'s life path 10 times.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: '⚠️ Missable — only possible in a single playthrough. Life path dialogue options (Street Kid, Nomad, or Corpo) appear marked with your background icon in dialogue. Use them whenever available throughout the game. There are well over 10 in the main story alone.',
  },
  {
    id: 'autojock',
    name: 'Autojock',
    desc: 'Buy all vehicles available for purchase.',
    tier: 'gold',
    category: 'Combat & Skills',
    guide: 'Purchase all 26 buyable vehicles from fixers across Night City. Costs approximately 1,722,000 Eurodollars total. Vehicles become available as you raise Street Cred in each district. Check your messages from fixers — each new contact unlocks more cars.',
  },
  {
    id: 'master_crafter',
    name: 'Master Crafter',
    desc: 'Craft 3 Legendary items.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Invest points in the Technical Ability attribute and unlock Legendary crafting perks. Gather Legendary crafting components (dropped by enemies or found in containers) and craft any 3 Legendary-tier items at the crafting menu.',
  },
  {
    id: 'daemon_in_the_shell',
    name: 'Daemon In The Shell',
    desc: 'Kill or incapacitate 3 enemies with one "Detonate Grenade" quickhack.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Unlock the "Detonate Grenade" quickhack (requires Intelligence investment). Find 3 enemies clustered together where at least one is carrying a grenade. Upload the quickhack to the grenade carrier and trigger the detonation to hit all three.',
  },
  {
    id: 'the_quick_and_the_dead',
    name: 'The Quick and the Dead',
    desc: 'Kill or incapacitate 50 enemies while time is slowed.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Equip a Sandevistan Operating System cyberware (Reflexes attribute). Activate it during combat — time slows dramatically. Kill 50 enemies total across any number of activations. The Militech Sandevistan is available early from Ripperdocs.',
  },
  {
    id: 'must_be_rats',
    name: 'Must Be Rats',
    desc: 'Perform the Distract Enemies quickhack 30 times without drawing attention to yourself.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Unlock the "Distract Enemies" quickhack and use it 30 times while remaining undetected. Equip a Cyberdeck and use it from stealth on cameras, devices, or enemies. Each successful use while hidden counts — grind through any enemy-populated area.',
  },
  {
    id: 'v_for_vendetta',
    name: 'V for Vendetta',
    desc: 'After reviving with Second Heart, kill or incapacitate the enemy who killed you within 5 seconds.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Equip the "Second Heart" Circulatory System cyberware (available from Ripperdocs). Let an enemy down you, then immediately kill that same enemy within 5 seconds of revival. Easiest with a shotgun or explosive — the attacker must be nearby.',
  },
  {
    id: 'true_soldier',
    name: 'True Soldier',
    desc: 'Kill or incapacitate 300 enemies using ranged weapons.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Kill 300 enemies with any gun. This will unlock naturally over a full playthrough. If grinding, NCPD Scanner Hustles respawn enemies and are a reliable source.',
  },
  {
    id: 'true_warrior',
    name: 'True Warrior',
    desc: 'Kill or incapacitate 100 enemies using melee weapons.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Kill 100 enemies with any melee weapon (Katanas, Mantis Blades, Gorilla Arms count). Use melee throughout the game or grind enemy camps. Gorilla Arms cyberware make this trivial in close-quarters fights.',
  },
  {
    id: 'right_back_at_ya',
    name: 'Right Back At Ya',
    desc: 'Kill or incapacitate an enemy who threw a grenade at you.',
    tier: 'bronze',
    category: 'Combat & Skills',
    guide: 'Let an enemy throw a grenade at you, then kill that specific enemy. Works easiest in fights with multiple Maelstrom or Militech soldiers who frequently use grenades. The kill does not need to be with the grenade itself — any method counts.',
  },

  // ── Exploration & Collectibles (8) ──

  {
    id: 'its_elementary',
    name: 'It\'s Elementary',
    desc: 'Complete all gigs and NCPD Scanner Hustles in Watson.',
    tier: 'silver',
    category: 'Exploration & Collectibles',
    guide: 'Complete every fixer gig and NCPD Scanner Hustle in the Watson district (Little China, Kabuki, Northside, Industrial District). Open your map, filter by gigs and hustles, and work through each one. Regina Jones is the fixer here.',
  },
  {
    id: 'greetings_from_pacifica',
    name: 'Greetings from Pacifica!',
    desc: 'Complete all gigs and NCPD Scanner Hustles in Pacifica.',
    tier: 'silver',
    category: 'Exploration & Collectibles',
    guide: 'Complete every fixer gig and NCPD Scanner Hustle in Pacifica (West Wind Estate, Coastview). Mr. Hands is the fixer here. Note: Pacifica has fewer gigs than other districts but the area is high-level, recommended for later in the game.',
  },
  {
    id: 'the_wasteland',
    name: 'The Wasteland',
    desc: 'Complete all gigs and NCPD Scanner Hustles in the Badlands.',
    tier: 'silver',
    category: 'Exploration & Collectibles',
    guide: 'Complete every fixer gig and NCPD Scanner Hustle in the Badlands (spread across a large area outside the city). Dakota Smith is the fixer here. Use a vehicle — the Badlands is vast. Check your map frequently for newly unlocked gigs.',
  },
  {
    id: 'little_tokyo',
    name: 'Little Tokyo',
    desc: 'Complete all gigs and NCPD Scanner Hustles in Westbrook.',
    tier: 'silver',
    category: 'Exploration & Collectibles',
    guide: 'Complete every fixer gig and NCPD Scanner Hustle in Westbrook (Japantown, Charter Hill, North Oak). Wakako Okada is the fixer here.',
  },
  {
    id: 'mean_streets',
    name: 'Mean Streets',
    desc: 'Complete all gigs and NCPD Scanner Hustles in Heywood.',
    tier: 'silver',
    category: 'Exploration & Collectibles',
    guide: 'Complete every fixer gig and NCPD Scanner Hustle in Heywood (The Glen, Vista del Rey, Wellsprings). Padre is the fixer here.',
  },
  {
    id: 'the_jungle',
    name: 'The Jungle',
    desc: 'Complete all gigs and NCPD Scanner Hustles in Santo Domingo.',
    tier: 'silver',
    category: 'Exploration & Collectibles',
    guide: 'Complete every fixer gig and NCPD Scanner Hustle in Santo Domingo (Arroyo, Rancho Coronado). Rogue initially covers this area. A fairly compact district — good to clear early.',
  },
  {
    id: 'city_lights',
    name: 'City Lights',
    desc: 'Complete all gigs and NCPD Scanner Hustles in City Center.',
    tier: 'silver',
    category: 'Exploration & Collectibles',
    guide: 'Complete every fixer gig and NCPD Scanner Hustle in City Center (Downtown, Corpo Plaza). Gigs here are unlocked at higher Street Cred levels. Corpo Plaza in particular has high-level enemies.',
  },
  {
    id: 'frequent_flyer',
    name: 'Frequent Flyer',
    desc: 'Find all fast travel dataterms.',
    tier: 'bronze',
    category: 'Exploration & Collectibles',
    guide: 'Discover all fast travel dataterm points across Night City and the Badlands. They appear as blue icons on the map once found. Simply drive or walk to each one to register it — no interaction required beyond approaching them.',
  },

  // ── Phantom Liberty (13) ──

  {
    id: 'king_of_wands',
    name: 'King of Wands',
    desc: 'Help Songbird escape.',
    tier: 'gold',
    category: 'Phantom Liberty',
    secret: true,
    guide: '⚠️ Phantom Liberty ending. During the final mission, side with Songbird and help her escape from both Reed and the NUSA. This requires building trust with So Mi throughout the DLC quests.',
  },
  {
    id: 'king_of_swords',
    name: 'King of Swords',
    desc: 'Take Songbird home.',
    tier: 'gold',
    category: 'Phantom Liberty',
    secret: true,
    guide: '⚠️ Phantom Liberty ending. Side with Solomon Reed and hand Songbird over to the NUSA/FIA. Follow Reed\'s path throughout the DLC and complete his requests to unlock this ending.',
  },
  {
    id: 'king_of_cups',
    name: 'King of Cups',
    desc: 'Kill Songbird.',
    tier: 'gold',
    category: 'Phantom Liberty',
    secret: true,
    guide: '⚠️ Phantom Liberty ending. During the final confrontation, choose to kill Songbird rather than help her escape or hand her to Reed. This ending requires specific choices in the final mission.',
  },
  {
    id: 'king_of_pentacles',
    name: 'King of Pentacles',
    desc: 'Spare Songbird.',
    tier: 'gold',
    category: 'Phantom Liberty',
    secret: true,
    guide: '⚠️ Phantom Liberty ending. Choose to spare Songbird\'s life rather than eliminating her. This ending requires specific dialogue and action choices during the final mission\'s confrontation.',
  },
  {
    id: 'the_tower',
    name: 'The Tower',
    desc: 'Complete "Things Done Changed."',
    tier: 'gold',
    category: 'Phantom Liberty',
    secret: true,
    guide: 'Complete the Phantom Liberty DLC\'s concluding mission "Things Done Changed." This unlocks after finishing the main Phantom Liberty questline regardless of ending chosen, and opens a new epilogue for V.',
  },
  {
    id: 'spin_doctor',
    name: 'Spin Doctor',
    desc: 'Complete "Run This Town."',
    tier: 'silver',
    category: 'Phantom Liberty',
    secret: true,
    guide: 'Complete the Phantom Liberty mission "Run This Town," which involves dealing with Kurt Hansen, the warlord controlling Dogtown. This is a key main story mission in the DLC.',
  },
  {
    id: 'all_the_presidents_men',
    name: 'All the President\'s Men',
    desc: 'Save President Myers.',
    tier: 'silver',
    category: 'Phantom Liberty',
    guide: 'Story related to Phantom Liberty, cannot be missed. Unlocks during the early Phantom Liberty missions when V rescues President Rosalind Myers from the crashed AV in Dogtown.',
  },
  {
    id: 'dirty_deeds',
    name: 'Dirty Deeds',
    desc: 'Complete every Gig in Dogtown.',
    tier: 'silver',
    category: 'Phantom Liberty',
    guide: 'Complete all gigs available in Dogtown (the Phantom Liberty area). Mr. Hands assigns most Dogtown gigs. Check your map with the Dogtown filter active — there are roughly 20 gigs total across the district.',
  },
  {
    id: 'arachnophobia',
    name: 'Arachnophobia',
    desc: 'Defeat the Chimera.',
    tier: 'bronze',
    category: 'Phantom Liberty',
    secret: true,
    guide: 'Story related to Phantom Liberty, cannot be missed. Defeat the Chimera, a massive spider-like military mech encountered during the early Phantom Liberty main quest in Dogtown.',
  },
  {
    id: 'relic_ruler',
    name: 'Relic Ruler',
    desc: 'Unlock all Perks in the Relic Perk tree.',
    tier: 'silver',
    category: 'Phantom Liberty',
    guide: 'Unlock all 15 perks in the Relic skill tree, which becomes available after installing the new Relic cyberware in Phantom Liberty. Earn Relic points by finding Militech Data Terminals hidden throughout Dogtown.',
  },
  {
    id: 'judgement_day',
    name: 'Judgement Day',
    desc: 'Eliminate three bosses from the "Increased criminal activity" category.',
    tier: 'bronze',
    category: 'Phantom Liberty',
    guide: 'Find and eliminate 3 bosses from the special "Increased criminal activity" NCPD events in Dogtown. These are marked with a distinct skull icon on the map and are tougher than standard NCPD hustles.',
  },
  {
    id: 'easy_come_easy_go',
    name: 'Easy Come, Easy Go',
    desc: 'Steal the Arasaka medical truck or deliver 10 vehicles to El Capitan.',
    tier: 'bronze',
    category: 'Phantom Liberty',
    guide: 'Either steal the special Arasaka medical truck during a Phantom Liberty gig, or complete 10 vehicle delivery contracts for El Capitan (the Dogtown fixer who assigns car-stealing jobs). The vehicle deliveries are the easier route.',
  },
  {
    id: 'the_apb_is_not_enough',
    name: 'The APB is Not Enough',
    desc: 'Become Dogtown\'s most wanted criminal.',
    tier: 'bronze',
    category: 'Phantom Liberty',
    guide: 'Reach a 5-star wanted level in Dogtown. Simply go on a rampage in Dogtown — attack Barghest soldiers until the wanted level maxes out. You don\'t need to survive the chase, just reach 5 stars.',
  },
]
